CRITICAL - 2023-01-02 05:28:46 --> Class "Locale" not found
in SYSTEMPATH\CodeIgniter.php on line 181.
 1 FCPATH\index.php(55): CodeIgniter\CodeIgniter->initialize()
ERROR - 2023-01-02 20:39:43 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'regs2858_igni660'@'localhost' (using password: YES) in C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:171
Stack trace:
#0 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(171): mysqli->real_connect('localhost', 'regs2858_igni66...', '8m47Y6]S-p', 'regs2858_igni66...', 3306, '', 0)
#1 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Session\Handlers\DatabaseHandler.php(91): CodeIgniter\Database\BaseConnection->initialize()
#3 [internal function]: CodeIgniter\Session\Handlers\DatabaseHandler->open('ci_sessions', 'ci_session')
#4 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Session\Session.php(918): session_start()
#5 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Session\Session.php(240): CodeIgniter\Session\Session->startSession()
#6 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Config\Services.php(665): CodeIgniter\Session\Session->start()
#7 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Config\BaseService.php(253): CodeIgniter\Config\Services::session(Object(Config\App), false)
#8 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Config\BaseService.php(194): CodeIgniter\Config\BaseService::__callStatic('session', Array)
#9 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Config\Services.php(637): CodeIgniter\Config\BaseService::getSharedInstance('session', NULL)
#10 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Config\BaseService.php(253): CodeIgniter\Config\Services::session()
#11 C:\xampp\htdocs\lltdemo\app\Controllers\BaseController.php(51): CodeIgniter\Config\BaseService::__callStatic('session', Array)
#12 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\CodeIgniter.php(867): App\Controllers\BaseController->initController(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), Object(CodeIgniter\Log\Logger))
#13 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\CodeIgniter.php(448): CodeIgniter\CodeIgniter->createController()
#14 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#15 C:\xampp\htdocs\lltdemo\public\index.php(67): CodeIgniter\CodeIgniter->run()
#16 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:215
Stack trace:
#0 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Session\Handlers\DatabaseHandler.php(91): CodeIgniter\Database\BaseConnection->initialize()
#2 [internal function]: CodeIgniter\Session\Handlers\DatabaseHandler->open('ci_sessions', 'ci_session')
#3 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Session\Session.php(918): session_start()
#4 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Session\Session.php(240): CodeIgniter\Session\Session->startSession()
#5 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Config\Services.php(665): CodeIgniter\Session\Session->start()
#6 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Config\BaseService.php(253): CodeIgniter\Config\Services::session(Object(Config\App), false)
#7 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Config\BaseService.php(194): CodeIgniter\Config\BaseService::__callStatic('session', Array)
#8 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Config\Services.php(637): CodeIgniter\Config\BaseService::getSharedInstance('session', NULL)
#9 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Config\BaseService.php(253): CodeIgniter\Config\Services::session()
#10 C:\xampp\htdocs\lltdemo\app\Controllers\BaseController.php(51): CodeIgniter\Config\BaseService::__callStatic('session', Array)
#11 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\CodeIgniter.php(867): App\Controllers\BaseController->initController(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), Object(CodeIgniter\Log\Logger))
#12 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\CodeIgniter.php(448): CodeIgniter\CodeIgniter->createController()
#13 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#14 C:\xampp\htdocs\lltdemo\public\index.php(67): CodeIgniter\CodeIgniter->run()
#15 {main}
CRITICAL - 2023-01-02 20:39:43 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 418.
 1 SYSTEMPATH\Session\Handlers\DatabaseHandler.php(91): CodeIgniter\Database\BaseConnection->initialize()
 2 [internal function]: CodeIgniter\Session\Handlers\DatabaseHandler->open('ci_sessions', 'ci_session')
 3 SYSTEMPATH\Session\Session.php(918): session_start()
 4 SYSTEMPATH\Session\Session.php(240): CodeIgniter\Session\Session->startSession()
 5 SYSTEMPATH\Config\Services.php(665): CodeIgniter\Session\Session->start()
 6 SYSTEMPATH\Config\BaseService.php(253): CodeIgniter\Config\Services::session(Object(Config\App), false)
 7 SYSTEMPATH\Config\BaseService.php(194): CodeIgniter\Config\BaseService::__callStatic('session', [...])
 8 SYSTEMPATH\Config\Services.php(637): CodeIgniter\Config\BaseService::getSharedInstance('session', null)
 9 SYSTEMPATH\Config\BaseService.php(253): CodeIgniter\Config\Services::session()
10 APPPATH\Controllers\BaseController.php(51): CodeIgniter\Config\BaseService::__callStatic('session', [])
11 SYSTEMPATH\CodeIgniter.php(867): App\Controllers\BaseController->initController(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), Object(CodeIgniter\Log\Logger))
12 SYSTEMPATH\CodeIgniter.php(448): CodeIgniter\CodeIgniter->createController()
13 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
14 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2023-01-02 20:39:44 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'regs2858_igni660'@'localhost' (using password: YES) in C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:171
Stack trace:
#0 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(171): mysqli->real_connect('localhost', 'regs2858_igni66...', '8m47Y6]S-p', 'regs2858_igni66...', 3306, '', 0)
#1 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Session\Handlers\DatabaseHandler.php(91): CodeIgniter\Database\BaseConnection->initialize()
#3 [internal function]: CodeIgniter\Session\Handlers\DatabaseHandler->open('ci_sessions', 'ci_session')
#4 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Session\Session.php(918): session_start()
#5 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Session\Session.php(240): CodeIgniter\Session\Session->startSession()
#6 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Config\Services.php(665): CodeIgniter\Session\Session->start()
#7 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Config\BaseService.php(253): CodeIgniter\Config\Services::session(Object(Config\App), false)
#8 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Config\BaseService.php(194): CodeIgniter\Config\BaseService::__callStatic('session', Array)
#9 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Config\Services.php(637): CodeIgniter\Config\BaseService::getSharedInstance('session', NULL)
#10 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Config\BaseService.php(253): CodeIgniter\Config\Services::session()
#11 C:\xampp\htdocs\lltdemo\app\Controllers\BaseController.php(51): CodeIgniter\Config\BaseService::__callStatic('session', Array)
#12 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\CodeIgniter.php(867): App\Controllers\BaseController->initController(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), Object(CodeIgniter\Log\Logger))
#13 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\CodeIgniter.php(448): CodeIgniter\CodeIgniter->createController()
#14 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#15 C:\xampp\htdocs\lltdemo\public\index.php(67): CodeIgniter\CodeIgniter->run()
#16 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:215
Stack trace:
#0 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Session\Handlers\DatabaseHandler.php(91): CodeIgniter\Database\BaseConnection->initialize()
#2 [internal function]: CodeIgniter\Session\Handlers\DatabaseHandler->open('ci_sessions', 'ci_session')
#3 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Session\Session.php(918): session_start()
#4 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Session\Session.php(240): CodeIgniter\Session\Session->startSession()
#5 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Config\Services.php(665): CodeIgniter\Session\Session->start()
#6 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Config\BaseService.php(253): CodeIgniter\Config\Services::session(Object(Config\App), false)
#7 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Config\BaseService.php(194): CodeIgniter\Config\BaseService::__callStatic('session', Array)
#8 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Config\Services.php(637): CodeIgniter\Config\BaseService::getSharedInstance('session', NULL)
#9 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Config\BaseService.php(253): CodeIgniter\Config\Services::session()
#10 C:\xampp\htdocs\lltdemo\app\Controllers\BaseController.php(51): CodeIgniter\Config\BaseService::__callStatic('session', Array)
#11 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\CodeIgniter.php(867): App\Controllers\BaseController->initController(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), Object(CodeIgniter\Log\Logger))
#12 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\CodeIgniter.php(448): CodeIgniter\CodeIgniter->createController()
#13 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#14 C:\xampp\htdocs\lltdemo\public\index.php(67): CodeIgniter\CodeIgniter->run()
#15 {main}
CRITICAL - 2023-01-02 20:39:44 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 418.
 1 SYSTEMPATH\Session\Handlers\DatabaseHandler.php(91): CodeIgniter\Database\BaseConnection->initialize()
 2 [internal function]: CodeIgniter\Session\Handlers\DatabaseHandler->open('ci_sessions', 'ci_session')
 3 SYSTEMPATH\Session\Session.php(918): session_start()
 4 SYSTEMPATH\Session\Session.php(240): CodeIgniter\Session\Session->startSession()
 5 SYSTEMPATH\Config\Services.php(665): CodeIgniter\Session\Session->start()
 6 SYSTEMPATH\Config\BaseService.php(253): CodeIgniter\Config\Services::session(Object(Config\App), false)
 7 SYSTEMPATH\Config\BaseService.php(194): CodeIgniter\Config\BaseService::__callStatic('session', [...])
 8 SYSTEMPATH\Config\Services.php(637): CodeIgniter\Config\BaseService::getSharedInstance('session', null)
 9 SYSTEMPATH\Config\BaseService.php(253): CodeIgniter\Config\Services::session()
10 APPPATH\Controllers\BaseController.php(51): CodeIgniter\Config\BaseService::__callStatic('session', [])
11 SYSTEMPATH\CodeIgniter.php(867): App\Controllers\BaseController->initController(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), Object(CodeIgniter\Log\Logger))
12 SYSTEMPATH\CodeIgniter.php(448): CodeIgniter\CodeIgniter->createController()
13 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
14 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2023-01-02 20:39:47 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'regs2858_igni660'@'localhost' (using password: YES) in C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:171
Stack trace:
#0 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(171): mysqli->real_connect('localhost', 'regs2858_igni66...', '8m47Y6]S-p', 'regs2858_igni66...', 3306, '', 0)
#1 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Session\Handlers\DatabaseHandler.php(91): CodeIgniter\Database\BaseConnection->initialize()
#3 [internal function]: CodeIgniter\Session\Handlers\DatabaseHandler->open('ci_sessions', 'ci_session')
#4 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Session\Session.php(918): session_start()
#5 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Session\Session.php(240): CodeIgniter\Session\Session->startSession()
#6 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Config\Services.php(665): CodeIgniter\Session\Session->start()
#7 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Config\BaseService.php(253): CodeIgniter\Config\Services::session(Object(Config\App), false)
#8 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Config\BaseService.php(194): CodeIgniter\Config\BaseService::__callStatic('session', Array)
#9 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Config\Services.php(637): CodeIgniter\Config\BaseService::getSharedInstance('session', NULL)
#10 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Config\BaseService.php(253): CodeIgniter\Config\Services::session()
#11 C:\xampp\htdocs\lltdemo\app\Controllers\BaseController.php(51): CodeIgniter\Config\BaseService::__callStatic('session', Array)
#12 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\CodeIgniter.php(867): App\Controllers\BaseController->initController(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), Object(CodeIgniter\Log\Logger))
#13 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\CodeIgniter.php(448): CodeIgniter\CodeIgniter->createController()
#14 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#15 C:\xampp\htdocs\lltdemo\public\index.php(67): CodeIgniter\CodeIgniter->run()
#16 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:215
Stack trace:
#0 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Session\Handlers\DatabaseHandler.php(91): CodeIgniter\Database\BaseConnection->initialize()
#2 [internal function]: CodeIgniter\Session\Handlers\DatabaseHandler->open('ci_sessions', 'ci_session')
#3 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Session\Session.php(918): session_start()
#4 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Session\Session.php(240): CodeIgniter\Session\Session->startSession()
#5 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Config\Services.php(665): CodeIgniter\Session\Session->start()
#6 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Config\BaseService.php(253): CodeIgniter\Config\Services::session(Object(Config\App), false)
#7 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Config\BaseService.php(194): CodeIgniter\Config\BaseService::__callStatic('session', Array)
#8 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Config\Services.php(637): CodeIgniter\Config\BaseService::getSharedInstance('session', NULL)
#9 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Config\BaseService.php(253): CodeIgniter\Config\Services::session()
#10 C:\xampp\htdocs\lltdemo\app\Controllers\BaseController.php(51): CodeIgniter\Config\BaseService::__callStatic('session', Array)
#11 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\CodeIgniter.php(867): App\Controllers\BaseController->initController(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), Object(CodeIgniter\Log\Logger))
#12 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\CodeIgniter.php(448): CodeIgniter\CodeIgniter->createController()
#13 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#14 C:\xampp\htdocs\lltdemo\public\index.php(67): CodeIgniter\CodeIgniter->run()
#15 {main}
CRITICAL - 2023-01-02 20:39:47 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 418.
 1 SYSTEMPATH\Session\Handlers\DatabaseHandler.php(91): CodeIgniter\Database\BaseConnection->initialize()
 2 [internal function]: CodeIgniter\Session\Handlers\DatabaseHandler->open('ci_sessions', 'ci_session')
 3 SYSTEMPATH\Session\Session.php(918): session_start()
 4 SYSTEMPATH\Session\Session.php(240): CodeIgniter\Session\Session->startSession()
 5 SYSTEMPATH\Config\Services.php(665): CodeIgniter\Session\Session->start()
 6 SYSTEMPATH\Config\BaseService.php(253): CodeIgniter\Config\Services::session(Object(Config\App), false)
 7 SYSTEMPATH\Config\BaseService.php(194): CodeIgniter\Config\BaseService::__callStatic('session', [...])
 8 SYSTEMPATH\Config\Services.php(637): CodeIgniter\Config\BaseService::getSharedInstance('session', null)
 9 SYSTEMPATH\Config\BaseService.php(253): CodeIgniter\Config\Services::session()
10 APPPATH\Controllers\BaseController.php(51): CodeIgniter\Config\BaseService::__callStatic('session', [])
11 SYSTEMPATH\CodeIgniter.php(867): App\Controllers\BaseController->initController(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), Object(CodeIgniter\Log\Logger))
12 SYSTEMPATH\CodeIgniter.php(448): CodeIgniter\CodeIgniter->createController()
13 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
14 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2023-01-02 20:47:02 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'regs2858_igni660'@'localhost' (using password: YES) in C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:171
Stack trace:
#0 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(171): mysqli->real_connect('localhost', 'regs2858_igni66...', '8m47Y6]S-p', 'regs2858_igni66...', 3306, '', 0)
#1 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Session\Handlers\DatabaseHandler.php(91): CodeIgniter\Database\BaseConnection->initialize()
#3 [internal function]: CodeIgniter\Session\Handlers\DatabaseHandler->open('ci_sessions', 'ci_session')
#4 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Session\Session.php(918): session_start()
#5 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Session\Session.php(240): CodeIgniter\Session\Session->startSession()
#6 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Config\Services.php(665): CodeIgniter\Session\Session->start()
#7 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Config\BaseService.php(253): CodeIgniter\Config\Services::session(Object(Config\App), false)
#8 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Config\BaseService.php(194): CodeIgniter\Config\BaseService::__callStatic('session', Array)
#9 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Config\Services.php(637): CodeIgniter\Config\BaseService::getSharedInstance('session', NULL)
#10 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Config\BaseService.php(253): CodeIgniter\Config\Services::session()
#11 C:\xampp\htdocs\lltdemo\app\Controllers\BaseController.php(51): CodeIgniter\Config\BaseService::__callStatic('session', Array)
#12 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\CodeIgniter.php(867): App\Controllers\BaseController->initController(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), Object(CodeIgniter\Log\Logger))
#13 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\CodeIgniter.php(448): CodeIgniter\CodeIgniter->createController()
#14 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#15 C:\xampp\htdocs\lltdemo\public\index.php(67): CodeIgniter\CodeIgniter->run()
#16 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:215
Stack trace:
#0 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Session\Handlers\DatabaseHandler.php(91): CodeIgniter\Database\BaseConnection->initialize()
#2 [internal function]: CodeIgniter\Session\Handlers\DatabaseHandler->open('ci_sessions', 'ci_session')
#3 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Session\Session.php(918): session_start()
#4 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Session\Session.php(240): CodeIgniter\Session\Session->startSession()
#5 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Config\Services.php(665): CodeIgniter\Session\Session->start()
#6 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Config\BaseService.php(253): CodeIgniter\Config\Services::session(Object(Config\App), false)
#7 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Config\BaseService.php(194): CodeIgniter\Config\BaseService::__callStatic('session', Array)
#8 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Config\Services.php(637): CodeIgniter\Config\BaseService::getSharedInstance('session', NULL)
#9 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Config\BaseService.php(253): CodeIgniter\Config\Services::session()
#10 C:\xampp\htdocs\lltdemo\app\Controllers\BaseController.php(51): CodeIgniter\Config\BaseService::__callStatic('session', Array)
#11 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\CodeIgniter.php(867): App\Controllers\BaseController->initController(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), Object(CodeIgniter\Log\Logger))
#12 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\CodeIgniter.php(448): CodeIgniter\CodeIgniter->createController()
#13 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#14 C:\xampp\htdocs\lltdemo\public\index.php(67): CodeIgniter\CodeIgniter->run()
#15 {main}
CRITICAL - 2023-01-02 20:47:02 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 418.
 1 SYSTEMPATH\Session\Handlers\DatabaseHandler.php(91): CodeIgniter\Database\BaseConnection->initialize()
 2 [internal function]: CodeIgniter\Session\Handlers\DatabaseHandler->open('ci_sessions', 'ci_session')
 3 SYSTEMPATH\Session\Session.php(918): session_start()
 4 SYSTEMPATH\Session\Session.php(240): CodeIgniter\Session\Session->startSession()
 5 SYSTEMPATH\Config\Services.php(665): CodeIgniter\Session\Session->start()
 6 SYSTEMPATH\Config\BaseService.php(253): CodeIgniter\Config\Services::session(Object(Config\App), false)
 7 SYSTEMPATH\Config\BaseService.php(194): CodeIgniter\Config\BaseService::__callStatic('session', [...])
 8 SYSTEMPATH\Config\Services.php(637): CodeIgniter\Config\BaseService::getSharedInstance('session', null)
 9 SYSTEMPATH\Config\BaseService.php(253): CodeIgniter\Config\Services::session()
10 APPPATH\Controllers\BaseController.php(51): CodeIgniter\Config\BaseService::__callStatic('session', [])
11 SYSTEMPATH\CodeIgniter.php(867): App\Controllers\BaseController->initController(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), Object(CodeIgniter\Log\Logger))
12 SYSTEMPATH\CodeIgniter.php(448): CodeIgniter\CodeIgniter->createController()
13 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
14 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2023-01-02 20:49:06 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'regs2858_igni660'@'localhost' (using password: YES) in C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:171
Stack trace:
#0 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(171): mysqli->real_connect('localhost', 'regs2858_igni66...', '8m47Y6]S-p', 'regs2858_igni66...', 3306, '', 0)
#1 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Session\Handlers\DatabaseHandler.php(91): CodeIgniter\Database\BaseConnection->initialize()
#3 [internal function]: CodeIgniter\Session\Handlers\DatabaseHandler->open('ci_sessions', 'ci_session')
#4 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Session\Session.php(918): session_start()
#5 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Session\Session.php(240): CodeIgniter\Session\Session->startSession()
#6 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Config\Services.php(665): CodeIgniter\Session\Session->start()
#7 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Config\BaseService.php(253): CodeIgniter\Config\Services::session(Object(Config\App), false)
#8 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Config\BaseService.php(194): CodeIgniter\Config\BaseService::__callStatic('session', Array)
#9 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Config\Services.php(637): CodeIgniter\Config\BaseService::getSharedInstance('session', NULL)
#10 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Config\BaseService.php(253): CodeIgniter\Config\Services::session()
#11 C:\xampp\htdocs\lltdemo\app\Controllers\BaseController.php(51): CodeIgniter\Config\BaseService::__callStatic('session', Array)
#12 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\CodeIgniter.php(867): App\Controllers\BaseController->initController(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), Object(CodeIgniter\Log\Logger))
#13 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\CodeIgniter.php(448): CodeIgniter\CodeIgniter->createController()
#14 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#15 C:\xampp\htdocs\lltdemo\public\index.php(67): CodeIgniter\CodeIgniter->run()
#16 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:215
Stack trace:
#0 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Session\Handlers\DatabaseHandler.php(91): CodeIgniter\Database\BaseConnection->initialize()
#2 [internal function]: CodeIgniter\Session\Handlers\DatabaseHandler->open('ci_sessions', 'ci_session')
#3 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Session\Session.php(918): session_start()
#4 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Session\Session.php(240): CodeIgniter\Session\Session->startSession()
#5 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Config\Services.php(665): CodeIgniter\Session\Session->start()
#6 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Config\BaseService.php(253): CodeIgniter\Config\Services::session(Object(Config\App), false)
#7 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Config\BaseService.php(194): CodeIgniter\Config\BaseService::__callStatic('session', Array)
#8 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Config\Services.php(637): CodeIgniter\Config\BaseService::getSharedInstance('session', NULL)
#9 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Config\BaseService.php(253): CodeIgniter\Config\Services::session()
#10 C:\xampp\htdocs\lltdemo\app\Controllers\BaseController.php(51): CodeIgniter\Config\BaseService::__callStatic('session', Array)
#11 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\CodeIgniter.php(867): App\Controllers\BaseController->initController(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), Object(CodeIgniter\Log\Logger))
#12 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\CodeIgniter.php(448): CodeIgniter\CodeIgniter->createController()
#13 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#14 C:\xampp\htdocs\lltdemo\public\index.php(67): CodeIgniter\CodeIgniter->run()
#15 {main}
CRITICAL - 2023-01-02 20:49:06 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 418.
 1 SYSTEMPATH\Session\Handlers\DatabaseHandler.php(91): CodeIgniter\Database\BaseConnection->initialize()
 2 [internal function]: CodeIgniter\Session\Handlers\DatabaseHandler->open('ci_sessions', 'ci_session')
 3 SYSTEMPATH\Session\Session.php(918): session_start()
 4 SYSTEMPATH\Session\Session.php(240): CodeIgniter\Session\Session->startSession()
 5 SYSTEMPATH\Config\Services.php(665): CodeIgniter\Session\Session->start()
 6 SYSTEMPATH\Config\BaseService.php(253): CodeIgniter\Config\Services::session(Object(Config\App), false)
 7 SYSTEMPATH\Config\BaseService.php(194): CodeIgniter\Config\BaseService::__callStatic('session', [...])
 8 SYSTEMPATH\Config\Services.php(637): CodeIgniter\Config\BaseService::getSharedInstance('session', null)
 9 SYSTEMPATH\Config\BaseService.php(253): CodeIgniter\Config\Services::session()
10 APPPATH\Controllers\BaseController.php(51): CodeIgniter\Config\BaseService::__callStatic('session', [])
11 SYSTEMPATH\CodeIgniter.php(867): App\Controllers\BaseController->initController(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), Object(CodeIgniter\Log\Logger))
12 SYSTEMPATH\CodeIgniter.php(448): CodeIgniter\CodeIgniter->createController()
13 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
14 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2023-01-02 20:49:09 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'regs2858_igni660'@'localhost' (using password: YES) in C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:171
Stack trace:
#0 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(171): mysqli->real_connect('localhost', 'regs2858_igni66...', '8m47Y6]S-p', 'regs2858_igni66...', 3306, '', 0)
#1 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Session\Handlers\DatabaseHandler.php(91): CodeIgniter\Database\BaseConnection->initialize()
#3 [internal function]: CodeIgniter\Session\Handlers\DatabaseHandler->open('ci_sessions', 'ci_session')
#4 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Session\Session.php(918): session_start()
#5 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Session\Session.php(240): CodeIgniter\Session\Session->startSession()
#6 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Config\Services.php(665): CodeIgniter\Session\Session->start()
#7 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Config\BaseService.php(253): CodeIgniter\Config\Services::session(Object(Config\App), false)
#8 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Config\BaseService.php(194): CodeIgniter\Config\BaseService::__callStatic('session', Array)
#9 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Config\Services.php(637): CodeIgniter\Config\BaseService::getSharedInstance('session', NULL)
#10 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Config\BaseService.php(253): CodeIgniter\Config\Services::session()
#11 C:\xampp\htdocs\lltdemo\app\Controllers\BaseController.php(51): CodeIgniter\Config\BaseService::__callStatic('session', Array)
#12 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\CodeIgniter.php(867): App\Controllers\BaseController->initController(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), Object(CodeIgniter\Log\Logger))
#13 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\CodeIgniter.php(448): CodeIgniter\CodeIgniter->createController()
#14 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#15 C:\xampp\htdocs\lltdemo\public\index.php(67): CodeIgniter\CodeIgniter->run()
#16 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:215
Stack trace:
#0 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Session\Handlers\DatabaseHandler.php(91): CodeIgniter\Database\BaseConnection->initialize()
#2 [internal function]: CodeIgniter\Session\Handlers\DatabaseHandler->open('ci_sessions', 'ci_session')
#3 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Session\Session.php(918): session_start()
#4 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Session\Session.php(240): CodeIgniter\Session\Session->startSession()
#5 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Config\Services.php(665): CodeIgniter\Session\Session->start()
#6 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Config\BaseService.php(253): CodeIgniter\Config\Services::session(Object(Config\App), false)
#7 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Config\BaseService.php(194): CodeIgniter\Config\BaseService::__callStatic('session', Array)
#8 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Config\Services.php(637): CodeIgniter\Config\BaseService::getSharedInstance('session', NULL)
#9 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Config\BaseService.php(253): CodeIgniter\Config\Services::session()
#10 C:\xampp\htdocs\lltdemo\app\Controllers\BaseController.php(51): CodeIgniter\Config\BaseService::__callStatic('session', Array)
#11 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\CodeIgniter.php(867): App\Controllers\BaseController->initController(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), Object(CodeIgniter\Log\Logger))
#12 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\CodeIgniter.php(448): CodeIgniter\CodeIgniter->createController()
#13 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#14 C:\xampp\htdocs\lltdemo\public\index.php(67): CodeIgniter\CodeIgniter->run()
#15 {main}
CRITICAL - 2023-01-02 20:49:09 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 418.
 1 SYSTEMPATH\Session\Handlers\DatabaseHandler.php(91): CodeIgniter\Database\BaseConnection->initialize()
 2 [internal function]: CodeIgniter\Session\Handlers\DatabaseHandler->open('ci_sessions', 'ci_session')
 3 SYSTEMPATH\Session\Session.php(918): session_start()
 4 SYSTEMPATH\Session\Session.php(240): CodeIgniter\Session\Session->startSession()
 5 SYSTEMPATH\Config\Services.php(665): CodeIgniter\Session\Session->start()
 6 SYSTEMPATH\Config\BaseService.php(253): CodeIgniter\Config\Services::session(Object(Config\App), false)
 7 SYSTEMPATH\Config\BaseService.php(194): CodeIgniter\Config\BaseService::__callStatic('session', [...])
 8 SYSTEMPATH\Config\Services.php(637): CodeIgniter\Config\BaseService::getSharedInstance('session', null)
 9 SYSTEMPATH\Config\BaseService.php(253): CodeIgniter\Config\Services::session()
10 APPPATH\Controllers\BaseController.php(51): CodeIgniter\Config\BaseService::__callStatic('session', [])
11 SYSTEMPATH\CodeIgniter.php(867): App\Controllers\BaseController->initController(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), Object(CodeIgniter\Log\Logger))
12 SYSTEMPATH\CodeIgniter.php(448): CodeIgniter\CodeIgniter->createController()
13 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
14 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2023-01-02 20:49:21 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'regs2858_igni660'@'localhost' (using password: YES) in C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:171
Stack trace:
#0 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(171): mysqli->real_connect('localhost', 'regs2858_igni66...', '8m47Y6]S-p', 'regs2858_igni66...', 3306, '', 0)
#1 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Session\Handlers\DatabaseHandler.php(91): CodeIgniter\Database\BaseConnection->initialize()
#3 [internal function]: CodeIgniter\Session\Handlers\DatabaseHandler->open('ci_sessions', 'ci_session')
#4 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Session\Session.php(918): session_start()
#5 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Session\Session.php(240): CodeIgniter\Session\Session->startSession()
#6 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Config\Services.php(665): CodeIgniter\Session\Session->start()
#7 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Config\BaseService.php(253): CodeIgniter\Config\Services::session(Object(Config\App), false)
#8 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Config\BaseService.php(194): CodeIgniter\Config\BaseService::__callStatic('session', Array)
#9 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Config\Services.php(637): CodeIgniter\Config\BaseService::getSharedInstance('session', NULL)
#10 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Config\BaseService.php(253): CodeIgniter\Config\Services::session()
#11 C:\xampp\htdocs\lltdemo\app\Controllers\BaseController.php(51): CodeIgniter\Config\BaseService::__callStatic('session', Array)
#12 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\CodeIgniter.php(867): App\Controllers\BaseController->initController(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), Object(CodeIgniter\Log\Logger))
#13 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\CodeIgniter.php(448): CodeIgniter\CodeIgniter->createController()
#14 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#15 C:\xampp\htdocs\lltdemo\public\index.php(67): CodeIgniter\CodeIgniter->run()
#16 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:215
Stack trace:
#0 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Session\Handlers\DatabaseHandler.php(91): CodeIgniter\Database\BaseConnection->initialize()
#2 [internal function]: CodeIgniter\Session\Handlers\DatabaseHandler->open('ci_sessions', 'ci_session')
#3 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Session\Session.php(918): session_start()
#4 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Session\Session.php(240): CodeIgniter\Session\Session->startSession()
#5 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Config\Services.php(665): CodeIgniter\Session\Session->start()
#6 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Config\BaseService.php(253): CodeIgniter\Config\Services::session(Object(Config\App), false)
#7 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Config\BaseService.php(194): CodeIgniter\Config\BaseService::__callStatic('session', Array)
#8 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Config\Services.php(637): CodeIgniter\Config\BaseService::getSharedInstance('session', NULL)
#9 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Config\BaseService.php(253): CodeIgniter\Config\Services::session()
#10 C:\xampp\htdocs\lltdemo\app\Controllers\BaseController.php(51): CodeIgniter\Config\BaseService::__callStatic('session', Array)
#11 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\CodeIgniter.php(867): App\Controllers\BaseController->initController(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), Object(CodeIgniter\Log\Logger))
#12 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\CodeIgniter.php(448): CodeIgniter\CodeIgniter->createController()
#13 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#14 C:\xampp\htdocs\lltdemo\public\index.php(67): CodeIgniter\CodeIgniter->run()
#15 {main}
CRITICAL - 2023-01-02 20:49:21 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 418.
 1 SYSTEMPATH\Session\Handlers\DatabaseHandler.php(91): CodeIgniter\Database\BaseConnection->initialize()
 2 [internal function]: CodeIgniter\Session\Handlers\DatabaseHandler->open('ci_sessions', 'ci_session')
 3 SYSTEMPATH\Session\Session.php(918): session_start()
 4 SYSTEMPATH\Session\Session.php(240): CodeIgniter\Session\Session->startSession()
 5 SYSTEMPATH\Config\Services.php(665): CodeIgniter\Session\Session->start()
 6 SYSTEMPATH\Config\BaseService.php(253): CodeIgniter\Config\Services::session(Object(Config\App), false)
 7 SYSTEMPATH\Config\BaseService.php(194): CodeIgniter\Config\BaseService::__callStatic('session', [...])
 8 SYSTEMPATH\Config\Services.php(637): CodeIgniter\Config\BaseService::getSharedInstance('session', null)
 9 SYSTEMPATH\Config\BaseService.php(253): CodeIgniter\Config\Services::session()
10 APPPATH\Controllers\BaseController.php(51): CodeIgniter\Config\BaseService::__callStatic('session', [])
11 SYSTEMPATH\CodeIgniter.php(867): App\Controllers\BaseController->initController(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), Object(CodeIgniter\Log\Logger))
12 SYSTEMPATH\CodeIgniter.php(448): CodeIgniter\CodeIgniter->createController()
13 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
14 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2023-01-02 20:49:48 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'regs2858_igni660'@'localhost' (using password: YES) in C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:171
Stack trace:
#0 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(171): mysqli->real_connect('localhost', 'regs2858_igni66...', '8m47Y6]S-p', 'regs2858_igni66...', 3306, '', 0)
#1 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Session\Handlers\DatabaseHandler.php(91): CodeIgniter\Database\BaseConnection->initialize()
#3 [internal function]: CodeIgniter\Session\Handlers\DatabaseHandler->open('ci_sessions', 'ci_session')
#4 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Session\Session.php(918): session_start()
#5 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Session\Session.php(240): CodeIgniter\Session\Session->startSession()
#6 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Config\Services.php(665): CodeIgniter\Session\Session->start()
#7 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Config\BaseService.php(253): CodeIgniter\Config\Services::session(Object(Config\App), false)
#8 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Config\BaseService.php(194): CodeIgniter\Config\BaseService::__callStatic('session', Array)
#9 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Config\Services.php(637): CodeIgniter\Config\BaseService::getSharedInstance('session', NULL)
#10 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Config\BaseService.php(253): CodeIgniter\Config\Services::session()
#11 C:\xampp\htdocs\lltdemo\app\Controllers\BaseController.php(51): CodeIgniter\Config\BaseService::__callStatic('session', Array)
#12 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\CodeIgniter.php(867): App\Controllers\BaseController->initController(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), Object(CodeIgniter\Log\Logger))
#13 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\CodeIgniter.php(448): CodeIgniter\CodeIgniter->createController()
#14 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#15 C:\xampp\htdocs\lltdemo\public\index.php(67): CodeIgniter\CodeIgniter->run()
#16 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:215
Stack trace:
#0 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Session\Handlers\DatabaseHandler.php(91): CodeIgniter\Database\BaseConnection->initialize()
#2 [internal function]: CodeIgniter\Session\Handlers\DatabaseHandler->open('ci_sessions', 'ci_session')
#3 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Session\Session.php(918): session_start()
#4 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Session\Session.php(240): CodeIgniter\Session\Session->startSession()
#5 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Config\Services.php(665): CodeIgniter\Session\Session->start()
#6 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Config\BaseService.php(253): CodeIgniter\Config\Services::session(Object(Config\App), false)
#7 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Config\BaseService.php(194): CodeIgniter\Config\BaseService::__callStatic('session', Array)
#8 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Config\Services.php(637): CodeIgniter\Config\BaseService::getSharedInstance('session', NULL)
#9 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Config\BaseService.php(253): CodeIgniter\Config\Services::session()
#10 C:\xampp\htdocs\lltdemo\app\Controllers\BaseController.php(51): CodeIgniter\Config\BaseService::__callStatic('session', Array)
#11 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\CodeIgniter.php(867): App\Controllers\BaseController->initController(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), Object(CodeIgniter\Log\Logger))
#12 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\CodeIgniter.php(448): CodeIgniter\CodeIgniter->createController()
#13 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#14 C:\xampp\htdocs\lltdemo\public\index.php(67): CodeIgniter\CodeIgniter->run()
#15 {main}
CRITICAL - 2023-01-02 20:49:48 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 418.
 1 SYSTEMPATH\Session\Handlers\DatabaseHandler.php(91): CodeIgniter\Database\BaseConnection->initialize()
 2 [internal function]: CodeIgniter\Session\Handlers\DatabaseHandler->open('ci_sessions', 'ci_session')
 3 SYSTEMPATH\Session\Session.php(918): session_start()
 4 SYSTEMPATH\Session\Session.php(240): CodeIgniter\Session\Session->startSession()
 5 SYSTEMPATH\Config\Services.php(665): CodeIgniter\Session\Session->start()
 6 SYSTEMPATH\Config\BaseService.php(253): CodeIgniter\Config\Services::session(Object(Config\App), false)
 7 SYSTEMPATH\Config\BaseService.php(194): CodeIgniter\Config\BaseService::__callStatic('session', [...])
 8 SYSTEMPATH\Config\Services.php(637): CodeIgniter\Config\BaseService::getSharedInstance('session', null)
 9 SYSTEMPATH\Config\BaseService.php(253): CodeIgniter\Config\Services::session()
10 APPPATH\Controllers\BaseController.php(51): CodeIgniter\Config\BaseService::__callStatic('session', [])
11 SYSTEMPATH\CodeIgniter.php(867): App\Controllers\BaseController->initController(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), Object(CodeIgniter\Log\Logger))
12 SYSTEMPATH\CodeIgniter.php(448): CodeIgniter\CodeIgniter->createController()
13 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
14 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2023-01-02 20:51:07 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'regs2858_igni660'@'localhost' (using password: YES) in C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:171
Stack trace:
#0 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(171): mysqli->real_connect('localhost', 'regs2858_igni66...', '8m47Y6]S-p', 'regs2858_igni66...', 3306, '', 0)
#1 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Session\Handlers\DatabaseHandler.php(91): CodeIgniter\Database\BaseConnection->initialize()
#3 [internal function]: CodeIgniter\Session\Handlers\DatabaseHandler->open('ci_sessions', 'ci_session')
#4 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Session\Session.php(918): session_start()
#5 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Session\Session.php(240): CodeIgniter\Session\Session->startSession()
#6 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Config\Services.php(665): CodeIgniter\Session\Session->start()
#7 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Config\BaseService.php(253): CodeIgniter\Config\Services::session(Object(Config\App), false)
#8 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Config\BaseService.php(194): CodeIgniter\Config\BaseService::__callStatic('session', Array)
#9 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Config\Services.php(637): CodeIgniter\Config\BaseService::getSharedInstance('session', NULL)
#10 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Config\BaseService.php(253): CodeIgniter\Config\Services::session()
#11 C:\xampp\htdocs\lltdemo\app\Controllers\BaseController.php(51): CodeIgniter\Config\BaseService::__callStatic('session', Array)
#12 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\CodeIgniter.php(867): App\Controllers\BaseController->initController(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), Object(CodeIgniter\Log\Logger))
#13 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\CodeIgniter.php(448): CodeIgniter\CodeIgniter->createController()
#14 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#15 C:\xampp\htdocs\lltdemo\public\index.php(67): CodeIgniter\CodeIgniter->run()
#16 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:215
Stack trace:
#0 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Session\Handlers\DatabaseHandler.php(91): CodeIgniter\Database\BaseConnection->initialize()
#2 [internal function]: CodeIgniter\Session\Handlers\DatabaseHandler->open('ci_sessions', 'ci_session')
#3 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Session\Session.php(918): session_start()
#4 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Session\Session.php(240): CodeIgniter\Session\Session->startSession()
#5 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Config\Services.php(665): CodeIgniter\Session\Session->start()
#6 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Config\BaseService.php(253): CodeIgniter\Config\Services::session(Object(Config\App), false)
#7 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Config\BaseService.php(194): CodeIgniter\Config\BaseService::__callStatic('session', Array)
#8 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Config\Services.php(637): CodeIgniter\Config\BaseService::getSharedInstance('session', NULL)
#9 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Config\BaseService.php(253): CodeIgniter\Config\Services::session()
#10 C:\xampp\htdocs\lltdemo\app\Controllers\BaseController.php(51): CodeIgniter\Config\BaseService::__callStatic('session', Array)
#11 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\CodeIgniter.php(867): App\Controllers\BaseController->initController(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), Object(CodeIgniter\Log\Logger))
#12 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\CodeIgniter.php(448): CodeIgniter\CodeIgniter->createController()
#13 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#14 C:\xampp\htdocs\lltdemo\public\index.php(67): CodeIgniter\CodeIgniter->run()
#15 {main}
CRITICAL - 2023-01-02 20:51:07 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 418.
 1 SYSTEMPATH\Session\Handlers\DatabaseHandler.php(91): CodeIgniter\Database\BaseConnection->initialize()
 2 [internal function]: CodeIgniter\Session\Handlers\DatabaseHandler->open('ci_sessions', 'ci_session')
 3 SYSTEMPATH\Session\Session.php(918): session_start()
 4 SYSTEMPATH\Session\Session.php(240): CodeIgniter\Session\Session->startSession()
 5 SYSTEMPATH\Config\Services.php(665): CodeIgniter\Session\Session->start()
 6 SYSTEMPATH\Config\BaseService.php(253): CodeIgniter\Config\Services::session(Object(Config\App), false)
 7 SYSTEMPATH\Config\BaseService.php(194): CodeIgniter\Config\BaseService::__callStatic('session', [...])
 8 SYSTEMPATH\Config\Services.php(637): CodeIgniter\Config\BaseService::getSharedInstance('session', null)
 9 SYSTEMPATH\Config\BaseService.php(253): CodeIgniter\Config\Services::session()
10 APPPATH\Controllers\BaseController.php(51): CodeIgniter\Config\BaseService::__callStatic('session', [])
11 SYSTEMPATH\CodeIgniter.php(867): App\Controllers\BaseController->initController(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), Object(CodeIgniter\Log\Logger))
12 SYSTEMPATH\CodeIgniter.php(448): CodeIgniter\CodeIgniter->createController()
13 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
14 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2023-01-02 20:51:14 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'regs2858_igni660'@'localhost' (using password: YES) in C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:171
Stack trace:
#0 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(171): mysqli->real_connect('localhost', 'regs2858_igni66...', '8m47Y6]S-p', 'regs2858_igni66...', 3306, '', 0)
#1 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Session\Handlers\DatabaseHandler.php(91): CodeIgniter\Database\BaseConnection->initialize()
#3 [internal function]: CodeIgniter\Session\Handlers\DatabaseHandler->open('ci_sessions', 'ci_session')
#4 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Session\Session.php(918): session_start()
#5 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Session\Session.php(240): CodeIgniter\Session\Session->startSession()
#6 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Config\Services.php(665): CodeIgniter\Session\Session->start()
#7 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Config\BaseService.php(253): CodeIgniter\Config\Services::session(Object(Config\App), false)
#8 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Config\BaseService.php(194): CodeIgniter\Config\BaseService::__callStatic('session', Array)
#9 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Config\Services.php(637): CodeIgniter\Config\BaseService::getSharedInstance('session', NULL)
#10 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Config\BaseService.php(253): CodeIgniter\Config\Services::session()
#11 C:\xampp\htdocs\lltdemo\app\Controllers\BaseController.php(51): CodeIgniter\Config\BaseService::__callStatic('session', Array)
#12 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\CodeIgniter.php(867): App\Controllers\BaseController->initController(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), Object(CodeIgniter\Log\Logger))
#13 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\CodeIgniter.php(448): CodeIgniter\CodeIgniter->createController()
#14 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#15 C:\xampp\htdocs\lltdemo\public\index.php(67): CodeIgniter\CodeIgniter->run()
#16 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:215
Stack trace:
#0 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Session\Handlers\DatabaseHandler.php(91): CodeIgniter\Database\BaseConnection->initialize()
#2 [internal function]: CodeIgniter\Session\Handlers\DatabaseHandler->open('ci_sessions', 'ci_session')
#3 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Session\Session.php(918): session_start()
#4 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Session\Session.php(240): CodeIgniter\Session\Session->startSession()
#5 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Config\Services.php(665): CodeIgniter\Session\Session->start()
#6 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Config\BaseService.php(253): CodeIgniter\Config\Services::session(Object(Config\App), false)
#7 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Config\BaseService.php(194): CodeIgniter\Config\BaseService::__callStatic('session', Array)
#8 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Config\Services.php(637): CodeIgniter\Config\BaseService::getSharedInstance('session', NULL)
#9 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Config\BaseService.php(253): CodeIgniter\Config\Services::session()
#10 C:\xampp\htdocs\lltdemo\app\Controllers\BaseController.php(51): CodeIgniter\Config\BaseService::__callStatic('session', Array)
#11 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\CodeIgniter.php(867): App\Controllers\BaseController->initController(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), Object(CodeIgniter\Log\Logger))
#12 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\CodeIgniter.php(448): CodeIgniter\CodeIgniter->createController()
#13 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#14 C:\xampp\htdocs\lltdemo\public\index.php(67): CodeIgniter\CodeIgniter->run()
#15 {main}
CRITICAL - 2023-01-02 20:51:14 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 418.
 1 SYSTEMPATH\Session\Handlers\DatabaseHandler.php(91): CodeIgniter\Database\BaseConnection->initialize()
 2 [internal function]: CodeIgniter\Session\Handlers\DatabaseHandler->open('ci_sessions', 'ci_session')
 3 SYSTEMPATH\Session\Session.php(918): session_start()
 4 SYSTEMPATH\Session\Session.php(240): CodeIgniter\Session\Session->startSession()
 5 SYSTEMPATH\Config\Services.php(665): CodeIgniter\Session\Session->start()
 6 SYSTEMPATH\Config\BaseService.php(253): CodeIgniter\Config\Services::session(Object(Config\App), false)
 7 SYSTEMPATH\Config\BaseService.php(194): CodeIgniter\Config\BaseService::__callStatic('session', [...])
 8 SYSTEMPATH\Config\Services.php(637): CodeIgniter\Config\BaseService::getSharedInstance('session', null)
 9 SYSTEMPATH\Config\BaseService.php(253): CodeIgniter\Config\Services::session()
10 APPPATH\Controllers\BaseController.php(51): CodeIgniter\Config\BaseService::__callStatic('session', [])
11 SYSTEMPATH\CodeIgniter.php(867): App\Controllers\BaseController->initController(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), Object(CodeIgniter\Log\Logger))
12 SYSTEMPATH\CodeIgniter.php(448): CodeIgniter\CodeIgniter->createController()
13 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
14 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2023-01-02 21:18:14 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'regs2858_igni660'@'localhost' (using password: YES) in C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:171
Stack trace:
#0 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(171): mysqli->real_connect('localhost', 'regs2858_igni66...', '8m47Y6]S-p', 'regs2858_igni66...', 3306, '', 0)
#1 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Session\Handlers\DatabaseHandler.php(91): CodeIgniter\Database\BaseConnection->initialize()
#3 [internal function]: CodeIgniter\Session\Handlers\DatabaseHandler->open('ci_sessions', 'ci_session')
#4 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Session\Session.php(918): session_start()
#5 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Session\Session.php(240): CodeIgniter\Session\Session->startSession()
#6 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Config\Services.php(665): CodeIgniter\Session\Session->start()
#7 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Config\BaseService.php(253): CodeIgniter\Config\Services::session(Object(Config\App), false)
#8 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Config\BaseService.php(194): CodeIgniter\Config\BaseService::__callStatic('session', Array)
#9 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Config\Services.php(637): CodeIgniter\Config\BaseService::getSharedInstance('session', NULL)
#10 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Config\BaseService.php(253): CodeIgniter\Config\Services::session()
#11 C:\xampp\htdocs\lltdemo\app\Controllers\BaseController.php(51): CodeIgniter\Config\BaseService::__callStatic('session', Array)
#12 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\CodeIgniter.php(867): App\Controllers\BaseController->initController(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), Object(CodeIgniter\Log\Logger))
#13 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\CodeIgniter.php(448): CodeIgniter\CodeIgniter->createController()
#14 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#15 C:\xampp\htdocs\lltdemo\public\index.php(67): CodeIgniter\CodeIgniter->run()
#16 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:215
Stack trace:
#0 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Session\Handlers\DatabaseHandler.php(91): CodeIgniter\Database\BaseConnection->initialize()
#2 [internal function]: CodeIgniter\Session\Handlers\DatabaseHandler->open('ci_sessions', 'ci_session')
#3 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Session\Session.php(918): session_start()
#4 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Session\Session.php(240): CodeIgniter\Session\Session->startSession()
#5 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Config\Services.php(665): CodeIgniter\Session\Session->start()
#6 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Config\BaseService.php(253): CodeIgniter\Config\Services::session(Object(Config\App), false)
#7 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Config\BaseService.php(194): CodeIgniter\Config\BaseService::__callStatic('session', Array)
#8 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Config\Services.php(637): CodeIgniter\Config\BaseService::getSharedInstance('session', NULL)
#9 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Config\BaseService.php(253): CodeIgniter\Config\Services::session()
#10 C:\xampp\htdocs\lltdemo\app\Controllers\BaseController.php(51): CodeIgniter\Config\BaseService::__callStatic('session', Array)
#11 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\CodeIgniter.php(867): App\Controllers\BaseController->initController(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), Object(CodeIgniter\Log\Logger))
#12 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\CodeIgniter.php(448): CodeIgniter\CodeIgniter->createController()
#13 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#14 C:\xampp\htdocs\lltdemo\public\index.php(67): CodeIgniter\CodeIgniter->run()
#15 {main}
CRITICAL - 2023-01-02 21:18:14 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 418.
 1 SYSTEMPATH\Session\Handlers\DatabaseHandler.php(91): CodeIgniter\Database\BaseConnection->initialize()
 2 [internal function]: CodeIgniter\Session\Handlers\DatabaseHandler->open('ci_sessions', 'ci_session')
 3 SYSTEMPATH\Session\Session.php(918): session_start()
 4 SYSTEMPATH\Session\Session.php(240): CodeIgniter\Session\Session->startSession()
 5 SYSTEMPATH\Config\Services.php(665): CodeIgniter\Session\Session->start()
 6 SYSTEMPATH\Config\BaseService.php(253): CodeIgniter\Config\Services::session(Object(Config\App), false)
 7 SYSTEMPATH\Config\BaseService.php(194): CodeIgniter\Config\BaseService::__callStatic('session', [...])
 8 SYSTEMPATH\Config\Services.php(637): CodeIgniter\Config\BaseService::getSharedInstance('session', null)
 9 SYSTEMPATH\Config\BaseService.php(253): CodeIgniter\Config\Services::session()
10 APPPATH\Controllers\BaseController.php(51): CodeIgniter\Config\BaseService::__callStatic('session', [])
11 SYSTEMPATH\CodeIgniter.php(867): App\Controllers\BaseController->initController(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), Object(CodeIgniter\Log\Logger))
12 SYSTEMPATH\CodeIgniter.php(448): CodeIgniter\CodeIgniter->createController()
13 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
14 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2023-01-02 21:18:15 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'regs2858_igni660'@'localhost' (using password: YES) in C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:171
Stack trace:
#0 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(171): mysqli->real_connect('localhost', 'regs2858_igni66...', '8m47Y6]S-p', 'regs2858_igni66...', 3306, '', 0)
#1 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Session\Handlers\DatabaseHandler.php(91): CodeIgniter\Database\BaseConnection->initialize()
#3 [internal function]: CodeIgniter\Session\Handlers\DatabaseHandler->open('ci_sessions', 'ci_session')
#4 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Session\Session.php(918): session_start()
#5 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Session\Session.php(240): CodeIgniter\Session\Session->startSession()
#6 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Config\Services.php(665): CodeIgniter\Session\Session->start()
#7 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Config\BaseService.php(253): CodeIgniter\Config\Services::session(Object(Config\App), false)
#8 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Config\BaseService.php(194): CodeIgniter\Config\BaseService::__callStatic('session', Array)
#9 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Config\Services.php(637): CodeIgniter\Config\BaseService::getSharedInstance('session', NULL)
#10 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Config\BaseService.php(253): CodeIgniter\Config\Services::session()
#11 C:\xampp\htdocs\lltdemo\app\Controllers\BaseController.php(51): CodeIgniter\Config\BaseService::__callStatic('session', Array)
#12 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\CodeIgniter.php(867): App\Controllers\BaseController->initController(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), Object(CodeIgniter\Log\Logger))
#13 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\CodeIgniter.php(448): CodeIgniter\CodeIgniter->createController()
#14 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#15 C:\xampp\htdocs\lltdemo\public\index.php(67): CodeIgniter\CodeIgniter->run()
#16 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:215
Stack trace:
#0 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Session\Handlers\DatabaseHandler.php(91): CodeIgniter\Database\BaseConnection->initialize()
#2 [internal function]: CodeIgniter\Session\Handlers\DatabaseHandler->open('ci_sessions', 'ci_session')
#3 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Session\Session.php(918): session_start()
#4 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Session\Session.php(240): CodeIgniter\Session\Session->startSession()
#5 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Config\Services.php(665): CodeIgniter\Session\Session->start()
#6 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Config\BaseService.php(253): CodeIgniter\Config\Services::session(Object(Config\App), false)
#7 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Config\BaseService.php(194): CodeIgniter\Config\BaseService::__callStatic('session', Array)
#8 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Config\Services.php(637): CodeIgniter\Config\BaseService::getSharedInstance('session', NULL)
#9 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Config\BaseService.php(253): CodeIgniter\Config\Services::session()
#10 C:\xampp\htdocs\lltdemo\app\Controllers\BaseController.php(51): CodeIgniter\Config\BaseService::__callStatic('session', Array)
#11 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\CodeIgniter.php(867): App\Controllers\BaseController->initController(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), Object(CodeIgniter\Log\Logger))
#12 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\CodeIgniter.php(448): CodeIgniter\CodeIgniter->createController()
#13 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#14 C:\xampp\htdocs\lltdemo\public\index.php(67): CodeIgniter\CodeIgniter->run()
#15 {main}
CRITICAL - 2023-01-02 21:18:15 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 418.
 1 SYSTEMPATH\Session\Handlers\DatabaseHandler.php(91): CodeIgniter\Database\BaseConnection->initialize()
 2 [internal function]: CodeIgniter\Session\Handlers\DatabaseHandler->open('ci_sessions', 'ci_session')
 3 SYSTEMPATH\Session\Session.php(918): session_start()
 4 SYSTEMPATH\Session\Session.php(240): CodeIgniter\Session\Session->startSession()
 5 SYSTEMPATH\Config\Services.php(665): CodeIgniter\Session\Session->start()
 6 SYSTEMPATH\Config\BaseService.php(253): CodeIgniter\Config\Services::session(Object(Config\App), false)
 7 SYSTEMPATH\Config\BaseService.php(194): CodeIgniter\Config\BaseService::__callStatic('session', [...])
 8 SYSTEMPATH\Config\Services.php(637): CodeIgniter\Config\BaseService::getSharedInstance('session', null)
 9 SYSTEMPATH\Config\BaseService.php(253): CodeIgniter\Config\Services::session()
10 APPPATH\Controllers\BaseController.php(51): CodeIgniter\Config\BaseService::__callStatic('session', [])
11 SYSTEMPATH\CodeIgniter.php(867): App\Controllers\BaseController->initController(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), Object(CodeIgniter\Log\Logger))
12 SYSTEMPATH\CodeIgniter.php(448): CodeIgniter\CodeIgniter->createController()
13 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
14 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2023-01-02 21:18:15 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'regs2858_igni660'@'localhost' (using password: YES) in C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:171
Stack trace:
#0 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(171): mysqli->real_connect('localhost', 'regs2858_igni66...', '8m47Y6]S-p', 'regs2858_igni66...', 3306, '', 0)
#1 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Session\Handlers\DatabaseHandler.php(91): CodeIgniter\Database\BaseConnection->initialize()
#3 [internal function]: CodeIgniter\Session\Handlers\DatabaseHandler->open('ci_sessions', 'ci_session')
#4 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Session\Session.php(918): session_start()
#5 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Session\Session.php(240): CodeIgniter\Session\Session->startSession()
#6 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Config\Services.php(665): CodeIgniter\Session\Session->start()
#7 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Config\BaseService.php(253): CodeIgniter\Config\Services::session(Object(Config\App), false)
#8 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Config\BaseService.php(194): CodeIgniter\Config\BaseService::__callStatic('session', Array)
#9 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Config\Services.php(637): CodeIgniter\Config\BaseService::getSharedInstance('session', NULL)
#10 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Config\BaseService.php(253): CodeIgniter\Config\Services::session()
#11 C:\xampp\htdocs\lltdemo\app\Controllers\BaseController.php(51): CodeIgniter\Config\BaseService::__callStatic('session', Array)
#12 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\CodeIgniter.php(867): App\Controllers\BaseController->initController(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), Object(CodeIgniter\Log\Logger))
#13 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\CodeIgniter.php(448): CodeIgniter\CodeIgniter->createController()
#14 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#15 C:\xampp\htdocs\lltdemo\public\index.php(67): CodeIgniter\CodeIgniter->run()
#16 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:215
Stack trace:
#0 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Session\Handlers\DatabaseHandler.php(91): CodeIgniter\Database\BaseConnection->initialize()
#2 [internal function]: CodeIgniter\Session\Handlers\DatabaseHandler->open('ci_sessions', 'ci_session')
#3 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Session\Session.php(918): session_start()
#4 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Session\Session.php(240): CodeIgniter\Session\Session->startSession()
#5 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Config\Services.php(665): CodeIgniter\Session\Session->start()
#6 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Config\BaseService.php(253): CodeIgniter\Config\Services::session(Object(Config\App), false)
#7 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Config\BaseService.php(194): CodeIgniter\Config\BaseService::__callStatic('session', Array)
#8 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Config\Services.php(637): CodeIgniter\Config\BaseService::getSharedInstance('session', NULL)
#9 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Config\BaseService.php(253): CodeIgniter\Config\Services::session()
#10 C:\xampp\htdocs\lltdemo\app\Controllers\BaseController.php(51): CodeIgniter\Config\BaseService::__callStatic('session', Array)
#11 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\CodeIgniter.php(867): App\Controllers\BaseController->initController(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), Object(CodeIgniter\Log\Logger))
#12 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\CodeIgniter.php(448): CodeIgniter\CodeIgniter->createController()
#13 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#14 C:\xampp\htdocs\lltdemo\public\index.php(67): CodeIgniter\CodeIgniter->run()
#15 {main}
CRITICAL - 2023-01-02 21:18:15 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 418.
 1 SYSTEMPATH\Session\Handlers\DatabaseHandler.php(91): CodeIgniter\Database\BaseConnection->initialize()
 2 [internal function]: CodeIgniter\Session\Handlers\DatabaseHandler->open('ci_sessions', 'ci_session')
 3 SYSTEMPATH\Session\Session.php(918): session_start()
 4 SYSTEMPATH\Session\Session.php(240): CodeIgniter\Session\Session->startSession()
 5 SYSTEMPATH\Config\Services.php(665): CodeIgniter\Session\Session->start()
 6 SYSTEMPATH\Config\BaseService.php(253): CodeIgniter\Config\Services::session(Object(Config\App), false)
 7 SYSTEMPATH\Config\BaseService.php(194): CodeIgniter\Config\BaseService::__callStatic('session', [...])
 8 SYSTEMPATH\Config\Services.php(637): CodeIgniter\Config\BaseService::getSharedInstance('session', null)
 9 SYSTEMPATH\Config\BaseService.php(253): CodeIgniter\Config\Services::session()
10 APPPATH\Controllers\BaseController.php(51): CodeIgniter\Config\BaseService::__callStatic('session', [])
11 SYSTEMPATH\CodeIgniter.php(867): App\Controllers\BaseController->initController(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), Object(CodeIgniter\Log\Logger))
12 SYSTEMPATH\CodeIgniter.php(448): CodeIgniter\CodeIgniter->createController()
13 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
14 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2023-01-02 21:18:15 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'regs2858_igni660'@'localhost' (using password: YES) in C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:171
Stack trace:
#0 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(171): mysqli->real_connect('localhost', 'regs2858_igni66...', '8m47Y6]S-p', 'regs2858_igni66...', 3306, '', 0)
#1 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Session\Handlers\DatabaseHandler.php(91): CodeIgniter\Database\BaseConnection->initialize()
#3 [internal function]: CodeIgniter\Session\Handlers\DatabaseHandler->open('ci_sessions', 'ci_session')
#4 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Session\Session.php(918): session_start()
#5 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Session\Session.php(240): CodeIgniter\Session\Session->startSession()
#6 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Config\Services.php(665): CodeIgniter\Session\Session->start()
#7 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Config\BaseService.php(253): CodeIgniter\Config\Services::session(Object(Config\App), false)
#8 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Config\BaseService.php(194): CodeIgniter\Config\BaseService::__callStatic('session', Array)
#9 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Config\Services.php(637): CodeIgniter\Config\BaseService::getSharedInstance('session', NULL)
#10 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Config\BaseService.php(253): CodeIgniter\Config\Services::session()
#11 C:\xampp\htdocs\lltdemo\app\Controllers\BaseController.php(51): CodeIgniter\Config\BaseService::__callStatic('session', Array)
#12 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\CodeIgniter.php(867): App\Controllers\BaseController->initController(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), Object(CodeIgniter\Log\Logger))
#13 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\CodeIgniter.php(448): CodeIgniter\CodeIgniter->createController()
#14 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#15 C:\xampp\htdocs\lltdemo\public\index.php(67): CodeIgniter\CodeIgniter->run()
#16 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:215
Stack trace:
#0 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Session\Handlers\DatabaseHandler.php(91): CodeIgniter\Database\BaseConnection->initialize()
#2 [internal function]: CodeIgniter\Session\Handlers\DatabaseHandler->open('ci_sessions', 'ci_session')
#3 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Session\Session.php(918): session_start()
#4 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Session\Session.php(240): CodeIgniter\Session\Session->startSession()
#5 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Config\Services.php(665): CodeIgniter\Session\Session->start()
#6 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Config\BaseService.php(253): CodeIgniter\Config\Services::session(Object(Config\App), false)
#7 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Config\BaseService.php(194): CodeIgniter\Config\BaseService::__callStatic('session', Array)
#8 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Config\Services.php(637): CodeIgniter\Config\BaseService::getSharedInstance('session', NULL)
#9 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Config\BaseService.php(253): CodeIgniter\Config\Services::session()
#10 C:\xampp\htdocs\lltdemo\app\Controllers\BaseController.php(51): CodeIgniter\Config\BaseService::__callStatic('session', Array)
#11 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\CodeIgniter.php(867): App\Controllers\BaseController->initController(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), Object(CodeIgniter\Log\Logger))
#12 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\CodeIgniter.php(448): CodeIgniter\CodeIgniter->createController()
#13 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#14 C:\xampp\htdocs\lltdemo\public\index.php(67): CodeIgniter\CodeIgniter->run()
#15 {main}
CRITICAL - 2023-01-02 21:18:15 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 418.
 1 SYSTEMPATH\Session\Handlers\DatabaseHandler.php(91): CodeIgniter\Database\BaseConnection->initialize()
 2 [internal function]: CodeIgniter\Session\Handlers\DatabaseHandler->open('ci_sessions', 'ci_session')
 3 SYSTEMPATH\Session\Session.php(918): session_start()
 4 SYSTEMPATH\Session\Session.php(240): CodeIgniter\Session\Session->startSession()
 5 SYSTEMPATH\Config\Services.php(665): CodeIgniter\Session\Session->start()
 6 SYSTEMPATH\Config\BaseService.php(253): CodeIgniter\Config\Services::session(Object(Config\App), false)
 7 SYSTEMPATH\Config\BaseService.php(194): CodeIgniter\Config\BaseService::__callStatic('session', [...])
 8 SYSTEMPATH\Config\Services.php(637): CodeIgniter\Config\BaseService::getSharedInstance('session', null)
 9 SYSTEMPATH\Config\BaseService.php(253): CodeIgniter\Config\Services::session()
10 APPPATH\Controllers\BaseController.php(51): CodeIgniter\Config\BaseService::__callStatic('session', [])
11 SYSTEMPATH\CodeIgniter.php(867): App\Controllers\BaseController->initController(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), Object(CodeIgniter\Log\Logger))
12 SYSTEMPATH\CodeIgniter.php(448): CodeIgniter\CodeIgniter->createController()
13 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
14 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2023-01-02 21:21:33 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'regs2858_igni660'@'localhost' (using password: YES) in C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:171
Stack trace:
#0 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(171): mysqli->real_connect('localhost', 'regs2858_igni66...', '8m47Y6]S-p', 'regs2858_igni66...', 3306, '', 0)
#1 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Session\Handlers\DatabaseHandler.php(91): CodeIgniter\Database\BaseConnection->initialize()
#3 [internal function]: CodeIgniter\Session\Handlers\DatabaseHandler->open('ci_sessions', 'ci_session')
#4 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Session\Session.php(918): session_start()
#5 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Session\Session.php(240): CodeIgniter\Session\Session->startSession()
#6 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Config\Services.php(665): CodeIgniter\Session\Session->start()
#7 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Config\BaseService.php(253): CodeIgniter\Config\Services::session(Object(Config\App), false)
#8 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Config\BaseService.php(194): CodeIgniter\Config\BaseService::__callStatic('session', Array)
#9 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Config\Services.php(637): CodeIgniter\Config\BaseService::getSharedInstance('session', NULL)
#10 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Config\BaseService.php(253): CodeIgniter\Config\Services::session()
#11 C:\xampp\htdocs\lltdemo\app\Controllers\BaseController.php(51): CodeIgniter\Config\BaseService::__callStatic('session', Array)
#12 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\CodeIgniter.php(867): App\Controllers\BaseController->initController(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), Object(CodeIgniter\Log\Logger))
#13 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\CodeIgniter.php(448): CodeIgniter\CodeIgniter->createController()
#14 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#15 C:\xampp\htdocs\lltdemo\public\index.php(67): CodeIgniter\CodeIgniter->run()
#16 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:215
Stack trace:
#0 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Session\Handlers\DatabaseHandler.php(91): CodeIgniter\Database\BaseConnection->initialize()
#2 [internal function]: CodeIgniter\Session\Handlers\DatabaseHandler->open('ci_sessions', 'ci_session')
#3 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Session\Session.php(918): session_start()
#4 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Session\Session.php(240): CodeIgniter\Session\Session->startSession()
#5 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Config\Services.php(665): CodeIgniter\Session\Session->start()
#6 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Config\BaseService.php(253): CodeIgniter\Config\Services::session(Object(Config\App), false)
#7 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Config\BaseService.php(194): CodeIgniter\Config\BaseService::__callStatic('session', Array)
#8 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Config\Services.php(637): CodeIgniter\Config\BaseService::getSharedInstance('session', NULL)
#9 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Config\BaseService.php(253): CodeIgniter\Config\Services::session()
#10 C:\xampp\htdocs\lltdemo\app\Controllers\BaseController.php(51): CodeIgniter\Config\BaseService::__callStatic('session', Array)
#11 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\CodeIgniter.php(867): App\Controllers\BaseController->initController(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), Object(CodeIgniter\Log\Logger))
#12 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\CodeIgniter.php(448): CodeIgniter\CodeIgniter->createController()
#13 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#14 C:\xampp\htdocs\lltdemo\public\index.php(67): CodeIgniter\CodeIgniter->run()
#15 {main}
CRITICAL - 2023-01-02 21:21:33 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 418.
 1 SYSTEMPATH\Session\Handlers\DatabaseHandler.php(91): CodeIgniter\Database\BaseConnection->initialize()
 2 [internal function]: CodeIgniter\Session\Handlers\DatabaseHandler->open('ci_sessions', 'ci_session')
 3 SYSTEMPATH\Session\Session.php(918): session_start()
 4 SYSTEMPATH\Session\Session.php(240): CodeIgniter\Session\Session->startSession()
 5 SYSTEMPATH\Config\Services.php(665): CodeIgniter\Session\Session->start()
 6 SYSTEMPATH\Config\BaseService.php(253): CodeIgniter\Config\Services::session(Object(Config\App), false)
 7 SYSTEMPATH\Config\BaseService.php(194): CodeIgniter\Config\BaseService::__callStatic('session', [...])
 8 SYSTEMPATH\Config\Services.php(637): CodeIgniter\Config\BaseService::getSharedInstance('session', null)
 9 SYSTEMPATH\Config\BaseService.php(253): CodeIgniter\Config\Services::session()
10 APPPATH\Controllers\BaseController.php(51): CodeIgniter\Config\BaseService::__callStatic('session', [])
11 SYSTEMPATH\CodeIgniter.php(867): App\Controllers\BaseController->initController(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), Object(CodeIgniter\Log\Logger))
12 SYSTEMPATH\CodeIgniter.php(448): CodeIgniter\CodeIgniter->createController()
13 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
14 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2023-01-02 21:22:33 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'regs2858_igni660'@'localhost' (using password: YES) in C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:171
Stack trace:
#0 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(171): mysqli->real_connect('localhost', 'regs2858_igni66...', '8m47Y6]S-p', 'regs2858_igni66...', 3306, '', 0)
#1 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Session\Handlers\DatabaseHandler.php(91): CodeIgniter\Database\BaseConnection->initialize()
#3 [internal function]: CodeIgniter\Session\Handlers\DatabaseHandler->open('ci_sessions', 'ci_session')
#4 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Session\Session.php(918): session_start()
#5 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Session\Session.php(240): CodeIgniter\Session\Session->startSession()
#6 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Config\Services.php(665): CodeIgniter\Session\Session->start()
#7 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Config\BaseService.php(253): CodeIgniter\Config\Services::session(Object(Config\App), false)
#8 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Config\BaseService.php(194): CodeIgniter\Config\BaseService::__callStatic('session', Array)
#9 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Config\Services.php(637): CodeIgniter\Config\BaseService::getSharedInstance('session', NULL)
#10 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Config\BaseService.php(253): CodeIgniter\Config\Services::session()
#11 C:\xampp\htdocs\lltdemo\app\Controllers\BaseController.php(51): CodeIgniter\Config\BaseService::__callStatic('session', Array)
#12 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\CodeIgniter.php(867): App\Controllers\BaseController->initController(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), Object(CodeIgniter\Log\Logger))
#13 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\CodeIgniter.php(448): CodeIgniter\CodeIgniter->createController()
#14 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#15 C:\xampp\htdocs\lltdemo\public\index.php(67): CodeIgniter\CodeIgniter->run()
#16 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:215
Stack trace:
#0 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Session\Handlers\DatabaseHandler.php(91): CodeIgniter\Database\BaseConnection->initialize()
#2 [internal function]: CodeIgniter\Session\Handlers\DatabaseHandler->open('ci_sessions', 'ci_session')
#3 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Session\Session.php(918): session_start()
#4 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Session\Session.php(240): CodeIgniter\Session\Session->startSession()
#5 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Config\Services.php(665): CodeIgniter\Session\Session->start()
#6 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Config\BaseService.php(253): CodeIgniter\Config\Services::session(Object(Config\App), false)
#7 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Config\BaseService.php(194): CodeIgniter\Config\BaseService::__callStatic('session', Array)
#8 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Config\Services.php(637): CodeIgniter\Config\BaseService::getSharedInstance('session', NULL)
#9 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Config\BaseService.php(253): CodeIgniter\Config\Services::session()
#10 C:\xampp\htdocs\lltdemo\app\Controllers\BaseController.php(51): CodeIgniter\Config\BaseService::__callStatic('session', Array)
#11 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\CodeIgniter.php(867): App\Controllers\BaseController->initController(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), Object(CodeIgniter\Log\Logger))
#12 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\CodeIgniter.php(448): CodeIgniter\CodeIgniter->createController()
#13 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#14 C:\xampp\htdocs\lltdemo\public\index.php(67): CodeIgniter\CodeIgniter->run()
#15 {main}
CRITICAL - 2023-01-02 21:22:33 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 418.
 1 SYSTEMPATH\Session\Handlers\DatabaseHandler.php(91): CodeIgniter\Database\BaseConnection->initialize()
 2 [internal function]: CodeIgniter\Session\Handlers\DatabaseHandler->open('ci_sessions', 'ci_session')
 3 SYSTEMPATH\Session\Session.php(918): session_start()
 4 SYSTEMPATH\Session\Session.php(240): CodeIgniter\Session\Session->startSession()
 5 SYSTEMPATH\Config\Services.php(665): CodeIgniter\Session\Session->start()
 6 SYSTEMPATH\Config\BaseService.php(253): CodeIgniter\Config\Services::session(Object(Config\App), false)
 7 SYSTEMPATH\Config\BaseService.php(194): CodeIgniter\Config\BaseService::__callStatic('session', [...])
 8 SYSTEMPATH\Config\Services.php(637): CodeIgniter\Config\BaseService::getSharedInstance('session', null)
 9 SYSTEMPATH\Config\BaseService.php(253): CodeIgniter\Config\Services::session()
10 APPPATH\Controllers\BaseController.php(51): CodeIgniter\Config\BaseService::__callStatic('session', [])
11 SYSTEMPATH\CodeIgniter.php(867): App\Controllers\BaseController->initController(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), Object(CodeIgniter\Log\Logger))
12 SYSTEMPATH\CodeIgniter.php(448): CodeIgniter\CodeIgniter->createController()
13 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
14 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2023-01-02 21:22:34 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'regs2858_igni660'@'localhost' (using password: YES) in C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:171
Stack trace:
#0 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(171): mysqli->real_connect('localhost', 'regs2858_igni66...', '8m47Y6]S-p', 'regs2858_igni66...', 3306, '', 0)
#1 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Session\Handlers\DatabaseHandler.php(91): CodeIgniter\Database\BaseConnection->initialize()
#3 [internal function]: CodeIgniter\Session\Handlers\DatabaseHandler->open('ci_sessions', 'ci_session')
#4 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Session\Session.php(918): session_start()
#5 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Session\Session.php(240): CodeIgniter\Session\Session->startSession()
#6 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Config\Services.php(665): CodeIgniter\Session\Session->start()
#7 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Config\BaseService.php(253): CodeIgniter\Config\Services::session(Object(Config\App), false)
#8 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Config\BaseService.php(194): CodeIgniter\Config\BaseService::__callStatic('session', Array)
#9 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Config\Services.php(637): CodeIgniter\Config\BaseService::getSharedInstance('session', NULL)
#10 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Config\BaseService.php(253): CodeIgniter\Config\Services::session()
#11 C:\xampp\htdocs\lltdemo\app\Controllers\BaseController.php(51): CodeIgniter\Config\BaseService::__callStatic('session', Array)
#12 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\CodeIgniter.php(867): App\Controllers\BaseController->initController(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), Object(CodeIgniter\Log\Logger))
#13 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\CodeIgniter.php(448): CodeIgniter\CodeIgniter->createController()
#14 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#15 C:\xampp\htdocs\lltdemo\public\index.php(67): CodeIgniter\CodeIgniter->run()
#16 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:215
Stack trace:
#0 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Session\Handlers\DatabaseHandler.php(91): CodeIgniter\Database\BaseConnection->initialize()
#2 [internal function]: CodeIgniter\Session\Handlers\DatabaseHandler->open('ci_sessions', 'ci_session')
#3 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Session\Session.php(918): session_start()
#4 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Session\Session.php(240): CodeIgniter\Session\Session->startSession()
#5 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Config\Services.php(665): CodeIgniter\Session\Session->start()
#6 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Config\BaseService.php(253): CodeIgniter\Config\Services::session(Object(Config\App), false)
#7 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Config\BaseService.php(194): CodeIgniter\Config\BaseService::__callStatic('session', Array)
#8 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Config\Services.php(637): CodeIgniter\Config\BaseService::getSharedInstance('session', NULL)
#9 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Config\BaseService.php(253): CodeIgniter\Config\Services::session()
#10 C:\xampp\htdocs\lltdemo\app\Controllers\BaseController.php(51): CodeIgniter\Config\BaseService::__callStatic('session', Array)
#11 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\CodeIgniter.php(867): App\Controllers\BaseController->initController(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), Object(CodeIgniter\Log\Logger))
#12 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\CodeIgniter.php(448): CodeIgniter\CodeIgniter->createController()
#13 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#14 C:\xampp\htdocs\lltdemo\public\index.php(67): CodeIgniter\CodeIgniter->run()
#15 {main}
CRITICAL - 2023-01-02 21:22:34 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 418.
 1 SYSTEMPATH\Session\Handlers\DatabaseHandler.php(91): CodeIgniter\Database\BaseConnection->initialize()
 2 [internal function]: CodeIgniter\Session\Handlers\DatabaseHandler->open('ci_sessions', 'ci_session')
 3 SYSTEMPATH\Session\Session.php(918): session_start()
 4 SYSTEMPATH\Session\Session.php(240): CodeIgniter\Session\Session->startSession()
 5 SYSTEMPATH\Config\Services.php(665): CodeIgniter\Session\Session->start()
 6 SYSTEMPATH\Config\BaseService.php(253): CodeIgniter\Config\Services::session(Object(Config\App), false)
 7 SYSTEMPATH\Config\BaseService.php(194): CodeIgniter\Config\BaseService::__callStatic('session', [...])
 8 SYSTEMPATH\Config\Services.php(637): CodeIgniter\Config\BaseService::getSharedInstance('session', null)
 9 SYSTEMPATH\Config\BaseService.php(253): CodeIgniter\Config\Services::session()
10 APPPATH\Controllers\BaseController.php(51): CodeIgniter\Config\BaseService::__callStatic('session', [])
11 SYSTEMPATH\CodeIgniter.php(867): App\Controllers\BaseController->initController(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), Object(CodeIgniter\Log\Logger))
12 SYSTEMPATH\CodeIgniter.php(448): CodeIgniter\CodeIgniter->createController()
13 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
14 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2023-01-02 21:22:36 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'regs2858_igni660'@'localhost' (using password: YES) in C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:171
Stack trace:
#0 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(171): mysqli->real_connect('localhost', 'regs2858_igni66...', '8m47Y6]S-p', 'regs2858_igni66...', 3306, '', 0)
#1 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Session\Handlers\DatabaseHandler.php(91): CodeIgniter\Database\BaseConnection->initialize()
#3 [internal function]: CodeIgniter\Session\Handlers\DatabaseHandler->open('ci_sessions', 'ci_session')
#4 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Session\Session.php(918): session_start()
#5 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Session\Session.php(240): CodeIgniter\Session\Session->startSession()
#6 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Config\Services.php(665): CodeIgniter\Session\Session->start()
#7 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Config\BaseService.php(253): CodeIgniter\Config\Services::session(Object(Config\App), false)
#8 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Config\BaseService.php(194): CodeIgniter\Config\BaseService::__callStatic('session', Array)
#9 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Config\Services.php(637): CodeIgniter\Config\BaseService::getSharedInstance('session', NULL)
#10 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Config\BaseService.php(253): CodeIgniter\Config\Services::session()
#11 C:\xampp\htdocs\lltdemo\app\Controllers\BaseController.php(51): CodeIgniter\Config\BaseService::__callStatic('session', Array)
#12 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\CodeIgniter.php(867): App\Controllers\BaseController->initController(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), Object(CodeIgniter\Log\Logger))
#13 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\CodeIgniter.php(448): CodeIgniter\CodeIgniter->createController()
#14 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#15 C:\xampp\htdocs\lltdemo\public\index.php(67): CodeIgniter\CodeIgniter->run()
#16 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:215
Stack trace:
#0 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Session\Handlers\DatabaseHandler.php(91): CodeIgniter\Database\BaseConnection->initialize()
#2 [internal function]: CodeIgniter\Session\Handlers\DatabaseHandler->open('ci_sessions', 'ci_session')
#3 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Session\Session.php(918): session_start()
#4 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Session\Session.php(240): CodeIgniter\Session\Session->startSession()
#5 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Config\Services.php(665): CodeIgniter\Session\Session->start()
#6 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Config\BaseService.php(253): CodeIgniter\Config\Services::session(Object(Config\App), false)
#7 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Config\BaseService.php(194): CodeIgniter\Config\BaseService::__callStatic('session', Array)
#8 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Config\Services.php(637): CodeIgniter\Config\BaseService::getSharedInstance('session', NULL)
#9 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Config\BaseService.php(253): CodeIgniter\Config\Services::session()
#10 C:\xampp\htdocs\lltdemo\app\Controllers\BaseController.php(51): CodeIgniter\Config\BaseService::__callStatic('session', Array)
#11 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\CodeIgniter.php(867): App\Controllers\BaseController->initController(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), Object(CodeIgniter\Log\Logger))
#12 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\CodeIgniter.php(448): CodeIgniter\CodeIgniter->createController()
#13 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#14 C:\xampp\htdocs\lltdemo\public\index.php(67): CodeIgniter\CodeIgniter->run()
#15 {main}
CRITICAL - 2023-01-02 21:22:36 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 418.
 1 SYSTEMPATH\Session\Handlers\DatabaseHandler.php(91): CodeIgniter\Database\BaseConnection->initialize()
 2 [internal function]: CodeIgniter\Session\Handlers\DatabaseHandler->open('ci_sessions', 'ci_session')
 3 SYSTEMPATH\Session\Session.php(918): session_start()
 4 SYSTEMPATH\Session\Session.php(240): CodeIgniter\Session\Session->startSession()
 5 SYSTEMPATH\Config\Services.php(665): CodeIgniter\Session\Session->start()
 6 SYSTEMPATH\Config\BaseService.php(253): CodeIgniter\Config\Services::session(Object(Config\App), false)
 7 SYSTEMPATH\Config\BaseService.php(194): CodeIgniter\Config\BaseService::__callStatic('session', [...])
 8 SYSTEMPATH\Config\Services.php(637): CodeIgniter\Config\BaseService::getSharedInstance('session', null)
 9 SYSTEMPATH\Config\BaseService.php(253): CodeIgniter\Config\Services::session()
10 APPPATH\Controllers\BaseController.php(51): CodeIgniter\Config\BaseService::__callStatic('session', [])
11 SYSTEMPATH\CodeIgniter.php(867): App\Controllers\BaseController->initController(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), Object(CodeIgniter\Log\Logger))
12 SYSTEMPATH\CodeIgniter.php(448): CodeIgniter\CodeIgniter->createController()
13 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
14 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2023-01-02 21:23:33 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'regs2858_igni660'@'localhost' (using password: YES) in C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:171
Stack trace:
#0 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(171): mysqli->real_connect('localhost', 'regs2858_igni66...', '8m47Y6]S-p', 'regs2858_igni66...', 3306, '', 0)
#1 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Session\Handlers\DatabaseHandler.php(91): CodeIgniter\Database\BaseConnection->initialize()
#3 [internal function]: CodeIgniter\Session\Handlers\DatabaseHandler->open('ci_sessions', 'ci_session')
#4 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Session\Session.php(918): session_start()
#5 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Session\Session.php(240): CodeIgniter\Session\Session->startSession()
#6 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Config\Services.php(665): CodeIgniter\Session\Session->start()
#7 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Config\BaseService.php(253): CodeIgniter\Config\Services::session(Object(Config\App), false)
#8 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Config\BaseService.php(194): CodeIgniter\Config\BaseService::__callStatic('session', Array)
#9 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Config\Services.php(637): CodeIgniter\Config\BaseService::getSharedInstance('session', NULL)
#10 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Config\BaseService.php(253): CodeIgniter\Config\Services::session()
#11 C:\xampp\htdocs\lltdemo\app\Controllers\BaseController.php(51): CodeIgniter\Config\BaseService::__callStatic('session', Array)
#12 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\CodeIgniter.php(867): App\Controllers\BaseController->initController(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), Object(CodeIgniter\Log\Logger))
#13 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\CodeIgniter.php(448): CodeIgniter\CodeIgniter->createController()
#14 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#15 C:\xampp\htdocs\lltdemo\public\index.php(67): CodeIgniter\CodeIgniter->run()
#16 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:215
Stack trace:
#0 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Session\Handlers\DatabaseHandler.php(91): CodeIgniter\Database\BaseConnection->initialize()
#2 [internal function]: CodeIgniter\Session\Handlers\DatabaseHandler->open('ci_sessions', 'ci_session')
#3 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Session\Session.php(918): session_start()
#4 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Session\Session.php(240): CodeIgniter\Session\Session->startSession()
#5 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Config\Services.php(665): CodeIgniter\Session\Session->start()
#6 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Config\BaseService.php(253): CodeIgniter\Config\Services::session(Object(Config\App), false)
#7 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Config\BaseService.php(194): CodeIgniter\Config\BaseService::__callStatic('session', Array)
#8 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Config\Services.php(637): CodeIgniter\Config\BaseService::getSharedInstance('session', NULL)
#9 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Config\BaseService.php(253): CodeIgniter\Config\Services::session()
#10 C:\xampp\htdocs\lltdemo\app\Controllers\BaseController.php(51): CodeIgniter\Config\BaseService::__callStatic('session', Array)
#11 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\CodeIgniter.php(867): App\Controllers\BaseController->initController(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), Object(CodeIgniter\Log\Logger))
#12 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\CodeIgniter.php(448): CodeIgniter\CodeIgniter->createController()
#13 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#14 C:\xampp\htdocs\lltdemo\public\index.php(67): CodeIgniter\CodeIgniter->run()
#15 {main}
CRITICAL - 2023-01-02 21:23:33 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 418.
 1 SYSTEMPATH\Session\Handlers\DatabaseHandler.php(91): CodeIgniter\Database\BaseConnection->initialize()
 2 [internal function]: CodeIgniter\Session\Handlers\DatabaseHandler->open('ci_sessions', 'ci_session')
 3 SYSTEMPATH\Session\Session.php(918): session_start()
 4 SYSTEMPATH\Session\Session.php(240): CodeIgniter\Session\Session->startSession()
 5 SYSTEMPATH\Config\Services.php(665): CodeIgniter\Session\Session->start()
 6 SYSTEMPATH\Config\BaseService.php(253): CodeIgniter\Config\Services::session(Object(Config\App), false)
 7 SYSTEMPATH\Config\BaseService.php(194): CodeIgniter\Config\BaseService::__callStatic('session', [...])
 8 SYSTEMPATH\Config\Services.php(637): CodeIgniter\Config\BaseService::getSharedInstance('session', null)
 9 SYSTEMPATH\Config\BaseService.php(253): CodeIgniter\Config\Services::session()
10 APPPATH\Controllers\BaseController.php(51): CodeIgniter\Config\BaseService::__callStatic('session', [])
11 SYSTEMPATH\CodeIgniter.php(867): App\Controllers\BaseController->initController(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), Object(CodeIgniter\Log\Logger))
12 SYSTEMPATH\CodeIgniter.php(448): CodeIgniter\CodeIgniter->createController()
13 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
14 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2023-01-02 21:23:51 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'regs2858_igni660'@'localhost' (using password: YES) in C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:171
Stack trace:
#0 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(171): mysqli->real_connect('localhost', 'regs2858_igni66...', '8m47Y6]S-p', 'regs2858_igni66...', 3306, '', 0)
#1 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Session\Handlers\DatabaseHandler.php(91): CodeIgniter\Database\BaseConnection->initialize()
#3 [internal function]: CodeIgniter\Session\Handlers\DatabaseHandler->open('ci_sessions', 'ci_session')
#4 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Session\Session.php(918): session_start()
#5 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Session\Session.php(240): CodeIgniter\Session\Session->startSession()
#6 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Config\Services.php(665): CodeIgniter\Session\Session->start()
#7 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Config\BaseService.php(253): CodeIgniter\Config\Services::session(Object(Config\App), false)
#8 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Config\BaseService.php(194): CodeIgniter\Config\BaseService::__callStatic('session', Array)
#9 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Config\Services.php(637): CodeIgniter\Config\BaseService::getSharedInstance('session', NULL)
#10 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Config\BaseService.php(253): CodeIgniter\Config\Services::session()
#11 C:\xampp\htdocs\lltdemo\app\Controllers\BaseController.php(51): CodeIgniter\Config\BaseService::__callStatic('session', Array)
#12 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\CodeIgniter.php(867): App\Controllers\BaseController->initController(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), Object(CodeIgniter\Log\Logger))
#13 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\CodeIgniter.php(448): CodeIgniter\CodeIgniter->createController()
#14 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#15 C:\xampp\htdocs\lltdemo\public\index.php(67): CodeIgniter\CodeIgniter->run()
#16 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:215
Stack trace:
#0 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Session\Handlers\DatabaseHandler.php(91): CodeIgniter\Database\BaseConnection->initialize()
#2 [internal function]: CodeIgniter\Session\Handlers\DatabaseHandler->open('ci_sessions', 'ci_session')
#3 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Session\Session.php(918): session_start()
#4 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Session\Session.php(240): CodeIgniter\Session\Session->startSession()
#5 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Config\Services.php(665): CodeIgniter\Session\Session->start()
#6 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Config\BaseService.php(253): CodeIgniter\Config\Services::session(Object(Config\App), false)
#7 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Config\BaseService.php(194): CodeIgniter\Config\BaseService::__callStatic('session', Array)
#8 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Config\Services.php(637): CodeIgniter\Config\BaseService::getSharedInstance('session', NULL)
#9 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Config\BaseService.php(253): CodeIgniter\Config\Services::session()
#10 C:\xampp\htdocs\lltdemo\app\Controllers\BaseController.php(51): CodeIgniter\Config\BaseService::__callStatic('session', Array)
#11 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\CodeIgniter.php(867): App\Controllers\BaseController->initController(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), Object(CodeIgniter\Log\Logger))
#12 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\CodeIgniter.php(448): CodeIgniter\CodeIgniter->createController()
#13 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#14 C:\xampp\htdocs\lltdemo\public\index.php(67): CodeIgniter\CodeIgniter->run()
#15 {main}
CRITICAL - 2023-01-02 21:23:51 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 418.
 1 SYSTEMPATH\Session\Handlers\DatabaseHandler.php(91): CodeIgniter\Database\BaseConnection->initialize()
 2 [internal function]: CodeIgniter\Session\Handlers\DatabaseHandler->open('ci_sessions', 'ci_session')
 3 SYSTEMPATH\Session\Session.php(918): session_start()
 4 SYSTEMPATH\Session\Session.php(240): CodeIgniter\Session\Session->startSession()
 5 SYSTEMPATH\Config\Services.php(665): CodeIgniter\Session\Session->start()
 6 SYSTEMPATH\Config\BaseService.php(253): CodeIgniter\Config\Services::session(Object(Config\App), false)
 7 SYSTEMPATH\Config\BaseService.php(194): CodeIgniter\Config\BaseService::__callStatic('session', [...])
 8 SYSTEMPATH\Config\Services.php(637): CodeIgniter\Config\BaseService::getSharedInstance('session', null)
 9 SYSTEMPATH\Config\BaseService.php(253): CodeIgniter\Config\Services::session()
10 APPPATH\Controllers\BaseController.php(51): CodeIgniter\Config\BaseService::__callStatic('session', [])
11 SYSTEMPATH\CodeIgniter.php(867): App\Controllers\BaseController->initController(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), Object(CodeIgniter\Log\Logger))
12 SYSTEMPATH\CodeIgniter.php(448): CodeIgniter\CodeIgniter->createController()
13 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
14 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2023-01-02 21:23:52 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'regs2858_igni660'@'localhost' (using password: YES) in C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:171
Stack trace:
#0 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(171): mysqli->real_connect('localhost', 'regs2858_igni66...', '8m47Y6]S-p', 'regs2858_igni66...', 3306, '', 0)
#1 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Session\Handlers\DatabaseHandler.php(91): CodeIgniter\Database\BaseConnection->initialize()
#3 [internal function]: CodeIgniter\Session\Handlers\DatabaseHandler->open('ci_sessions', 'ci_session')
#4 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Session\Session.php(918): session_start()
#5 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Session\Session.php(240): CodeIgniter\Session\Session->startSession()
#6 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Config\Services.php(665): CodeIgniter\Session\Session->start()
#7 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Config\BaseService.php(253): CodeIgniter\Config\Services::session(Object(Config\App), false)
#8 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Config\BaseService.php(194): CodeIgniter\Config\BaseService::__callStatic('session', Array)
#9 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Config\Services.php(637): CodeIgniter\Config\BaseService::getSharedInstance('session', NULL)
#10 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Config\BaseService.php(253): CodeIgniter\Config\Services::session()
#11 C:\xampp\htdocs\lltdemo\app\Controllers\BaseController.php(51): CodeIgniter\Config\BaseService::__callStatic('session', Array)
#12 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\CodeIgniter.php(867): App\Controllers\BaseController->initController(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), Object(CodeIgniter\Log\Logger))
#13 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\CodeIgniter.php(448): CodeIgniter\CodeIgniter->createController()
#14 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#15 C:\xampp\htdocs\lltdemo\public\index.php(67): CodeIgniter\CodeIgniter->run()
#16 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:215
Stack trace:
#0 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Session\Handlers\DatabaseHandler.php(91): CodeIgniter\Database\BaseConnection->initialize()
#2 [internal function]: CodeIgniter\Session\Handlers\DatabaseHandler->open('ci_sessions', 'ci_session')
#3 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Session\Session.php(918): session_start()
#4 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Session\Session.php(240): CodeIgniter\Session\Session->startSession()
#5 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Config\Services.php(665): CodeIgniter\Session\Session->start()
#6 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Config\BaseService.php(253): CodeIgniter\Config\Services::session(Object(Config\App), false)
#7 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Config\BaseService.php(194): CodeIgniter\Config\BaseService::__callStatic('session', Array)
#8 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Config\Services.php(637): CodeIgniter\Config\BaseService::getSharedInstance('session', NULL)
#9 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Config\BaseService.php(253): CodeIgniter\Config\Services::session()
#10 C:\xampp\htdocs\lltdemo\app\Controllers\BaseController.php(51): CodeIgniter\Config\BaseService::__callStatic('session', Array)
#11 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\CodeIgniter.php(867): App\Controllers\BaseController->initController(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), Object(CodeIgniter\Log\Logger))
#12 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\CodeIgniter.php(448): CodeIgniter\CodeIgniter->createController()
#13 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#14 C:\xampp\htdocs\lltdemo\public\index.php(67): CodeIgniter\CodeIgniter->run()
#15 {main}
CRITICAL - 2023-01-02 21:23:52 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 418.
 1 SYSTEMPATH\Session\Handlers\DatabaseHandler.php(91): CodeIgniter\Database\BaseConnection->initialize()
 2 [internal function]: CodeIgniter\Session\Handlers\DatabaseHandler->open('ci_sessions', 'ci_session')
 3 SYSTEMPATH\Session\Session.php(918): session_start()
 4 SYSTEMPATH\Session\Session.php(240): CodeIgniter\Session\Session->startSession()
 5 SYSTEMPATH\Config\Services.php(665): CodeIgniter\Session\Session->start()
 6 SYSTEMPATH\Config\BaseService.php(253): CodeIgniter\Config\Services::session(Object(Config\App), false)
 7 SYSTEMPATH\Config\BaseService.php(194): CodeIgniter\Config\BaseService::__callStatic('session', [...])
 8 SYSTEMPATH\Config\Services.php(637): CodeIgniter\Config\BaseService::getSharedInstance('session', null)
 9 SYSTEMPATH\Config\BaseService.php(253): CodeIgniter\Config\Services::session()
10 APPPATH\Controllers\BaseController.php(51): CodeIgniter\Config\BaseService::__callStatic('session', [])
11 SYSTEMPATH\CodeIgniter.php(867): App\Controllers\BaseController->initController(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), Object(CodeIgniter\Log\Logger))
12 SYSTEMPATH\CodeIgniter.php(448): CodeIgniter\CodeIgniter->createController()
13 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
14 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2023-01-02 21:26:17 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'regs2858_igni660'@'localhost' (using password: YES) in C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:171
Stack trace:
#0 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(171): mysqli->real_connect('localhost', 'regs2858_igni66...', '8m47Y6]S-p', 'regs2858_igni66...', 3306, '', 0)
#1 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Session\Handlers\DatabaseHandler.php(91): CodeIgniter\Database\BaseConnection->initialize()
#3 [internal function]: CodeIgniter\Session\Handlers\DatabaseHandler->open('ci_sessions', 'ci_session')
#4 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Session\Session.php(918): session_start()
#5 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Session\Session.php(240): CodeIgniter\Session\Session->startSession()
#6 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Config\Services.php(665): CodeIgniter\Session\Session->start()
#7 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Config\BaseService.php(253): CodeIgniter\Config\Services::session(Object(Config\App), false)
#8 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Config\BaseService.php(194): CodeIgniter\Config\BaseService::__callStatic('session', Array)
#9 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Config\Services.php(637): CodeIgniter\Config\BaseService::getSharedInstance('session', NULL)
#10 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Config\BaseService.php(253): CodeIgniter\Config\Services::session()
#11 C:\xampp\htdocs\lltdemo\app\Controllers\BaseController.php(51): CodeIgniter\Config\BaseService::__callStatic('session', Array)
#12 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\CodeIgniter.php(867): App\Controllers\BaseController->initController(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), Object(CodeIgniter\Log\Logger))
#13 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\CodeIgniter.php(448): CodeIgniter\CodeIgniter->createController()
#14 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#15 C:\xampp\htdocs\lltdemo\public\index.php(67): CodeIgniter\CodeIgniter->run()
#16 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:215
Stack trace:
#0 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Session\Handlers\DatabaseHandler.php(91): CodeIgniter\Database\BaseConnection->initialize()
#2 [internal function]: CodeIgniter\Session\Handlers\DatabaseHandler->open('ci_sessions', 'ci_session')
#3 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Session\Session.php(918): session_start()
#4 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Session\Session.php(240): CodeIgniter\Session\Session->startSession()
#5 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Config\Services.php(665): CodeIgniter\Session\Session->start()
#6 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Config\BaseService.php(253): CodeIgniter\Config\Services::session(Object(Config\App), false)
#7 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Config\BaseService.php(194): CodeIgniter\Config\BaseService::__callStatic('session', Array)
#8 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Config\Services.php(637): CodeIgniter\Config\BaseService::getSharedInstance('session', NULL)
#9 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Config\BaseService.php(253): CodeIgniter\Config\Services::session()
#10 C:\xampp\htdocs\lltdemo\app\Controllers\BaseController.php(51): CodeIgniter\Config\BaseService::__callStatic('session', Array)
#11 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\CodeIgniter.php(867): App\Controllers\BaseController->initController(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), Object(CodeIgniter\Log\Logger))
#12 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\CodeIgniter.php(448): CodeIgniter\CodeIgniter->createController()
#13 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#14 C:\xampp\htdocs\lltdemo\public\index.php(67): CodeIgniter\CodeIgniter->run()
#15 {main}
CRITICAL - 2023-01-02 21:26:17 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 418.
 1 SYSTEMPATH\Session\Handlers\DatabaseHandler.php(91): CodeIgniter\Database\BaseConnection->initialize()
 2 [internal function]: CodeIgniter\Session\Handlers\DatabaseHandler->open('ci_sessions', 'ci_session')
 3 SYSTEMPATH\Session\Session.php(918): session_start()
 4 SYSTEMPATH\Session\Session.php(240): CodeIgniter\Session\Session->startSession()
 5 SYSTEMPATH\Config\Services.php(665): CodeIgniter\Session\Session->start()
 6 SYSTEMPATH\Config\BaseService.php(253): CodeIgniter\Config\Services::session(Object(Config\App), false)
 7 SYSTEMPATH\Config\BaseService.php(194): CodeIgniter\Config\BaseService::__callStatic('session', [...])
 8 SYSTEMPATH\Config\Services.php(637): CodeIgniter\Config\BaseService::getSharedInstance('session', null)
 9 SYSTEMPATH\Config\BaseService.php(253): CodeIgniter\Config\Services::session()
10 APPPATH\Controllers\BaseController.php(51): CodeIgniter\Config\BaseService::__callStatic('session', [])
11 SYSTEMPATH\CodeIgniter.php(867): App\Controllers\BaseController->initController(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), Object(CodeIgniter\Log\Logger))
12 SYSTEMPATH\CodeIgniter.php(448): CodeIgniter\CodeIgniter->createController()
13 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
14 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2023-01-02 21:26:18 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'regs2858_igni660'@'localhost' (using password: YES) in C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:171
Stack trace:
#0 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(171): mysqli->real_connect('localhost', 'regs2858_igni66...', '8m47Y6]S-p', 'regs2858_igni66...', 3306, '', 0)
#1 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Session\Handlers\DatabaseHandler.php(91): CodeIgniter\Database\BaseConnection->initialize()
#3 [internal function]: CodeIgniter\Session\Handlers\DatabaseHandler->open('ci_sessions', 'ci_session')
#4 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Session\Session.php(918): session_start()
#5 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Session\Session.php(240): CodeIgniter\Session\Session->startSession()
#6 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Config\Services.php(665): CodeIgniter\Session\Session->start()
#7 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Config\BaseService.php(253): CodeIgniter\Config\Services::session(Object(Config\App), false)
#8 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Config\BaseService.php(194): CodeIgniter\Config\BaseService::__callStatic('session', Array)
#9 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Config\Services.php(637): CodeIgniter\Config\BaseService::getSharedInstance('session', NULL)
#10 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Config\BaseService.php(253): CodeIgniter\Config\Services::session()
#11 C:\xampp\htdocs\lltdemo\app\Controllers\BaseController.php(51): CodeIgniter\Config\BaseService::__callStatic('session', Array)
#12 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\CodeIgniter.php(867): App\Controllers\BaseController->initController(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), Object(CodeIgniter\Log\Logger))
#13 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\CodeIgniter.php(448): CodeIgniter\CodeIgniter->createController()
#14 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#15 C:\xampp\htdocs\lltdemo\public\index.php(67): CodeIgniter\CodeIgniter->run()
#16 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:215
Stack trace:
#0 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Session\Handlers\DatabaseHandler.php(91): CodeIgniter\Database\BaseConnection->initialize()
#2 [internal function]: CodeIgniter\Session\Handlers\DatabaseHandler->open('ci_sessions', 'ci_session')
#3 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Session\Session.php(918): session_start()
#4 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Session\Session.php(240): CodeIgniter\Session\Session->startSession()
#5 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Config\Services.php(665): CodeIgniter\Session\Session->start()
#6 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Config\BaseService.php(253): CodeIgniter\Config\Services::session(Object(Config\App), false)
#7 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Config\BaseService.php(194): CodeIgniter\Config\BaseService::__callStatic('session', Array)
#8 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Config\Services.php(637): CodeIgniter\Config\BaseService::getSharedInstance('session', NULL)
#9 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Config\BaseService.php(253): CodeIgniter\Config\Services::session()
#10 C:\xampp\htdocs\lltdemo\app\Controllers\BaseController.php(51): CodeIgniter\Config\BaseService::__callStatic('session', Array)
#11 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\CodeIgniter.php(867): App\Controllers\BaseController->initController(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), Object(CodeIgniter\Log\Logger))
#12 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\CodeIgniter.php(448): CodeIgniter\CodeIgniter->createController()
#13 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#14 C:\xampp\htdocs\lltdemo\public\index.php(67): CodeIgniter\CodeIgniter->run()
#15 {main}
CRITICAL - 2023-01-02 21:26:18 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 418.
 1 SYSTEMPATH\Session\Handlers\DatabaseHandler.php(91): CodeIgniter\Database\BaseConnection->initialize()
 2 [internal function]: CodeIgniter\Session\Handlers\DatabaseHandler->open('ci_sessions', 'ci_session')
 3 SYSTEMPATH\Session\Session.php(918): session_start()
 4 SYSTEMPATH\Session\Session.php(240): CodeIgniter\Session\Session->startSession()
 5 SYSTEMPATH\Config\Services.php(665): CodeIgniter\Session\Session->start()
 6 SYSTEMPATH\Config\BaseService.php(253): CodeIgniter\Config\Services::session(Object(Config\App), false)
 7 SYSTEMPATH\Config\BaseService.php(194): CodeIgniter\Config\BaseService::__callStatic('session', [...])
 8 SYSTEMPATH\Config\Services.php(637): CodeIgniter\Config\BaseService::getSharedInstance('session', null)
 9 SYSTEMPATH\Config\BaseService.php(253): CodeIgniter\Config\Services::session()
10 APPPATH\Controllers\BaseController.php(51): CodeIgniter\Config\BaseService::__callStatic('session', [])
11 SYSTEMPATH\CodeIgniter.php(867): App\Controllers\BaseController->initController(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), Object(CodeIgniter\Log\Logger))
12 SYSTEMPATH\CodeIgniter.php(448): CodeIgniter\CodeIgniter->createController()
13 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
14 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2023-01-02 21:28:36 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'regs2858_igni660'@'localhost' (using password: YES) in C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:171
Stack trace:
#0 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(171): mysqli->real_connect('localhost', 'regs2858_igni66...', '8m47Y6]S-p', 'regs2858_igni66...', 3306, '', 0)
#1 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Session\Handlers\DatabaseHandler.php(91): CodeIgniter\Database\BaseConnection->initialize()
#3 [internal function]: CodeIgniter\Session\Handlers\DatabaseHandler->open('ci_sessions', 'ci_session')
#4 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Session\Session.php(918): session_start()
#5 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Session\Session.php(240): CodeIgniter\Session\Session->startSession()
#6 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Config\Services.php(665): CodeIgniter\Session\Session->start()
#7 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Config\BaseService.php(253): CodeIgniter\Config\Services::session(Object(Config\App), false)
#8 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Config\BaseService.php(194): CodeIgniter\Config\BaseService::__callStatic('session', Array)
#9 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Config\Services.php(637): CodeIgniter\Config\BaseService::getSharedInstance('session', NULL)
#10 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Config\BaseService.php(253): CodeIgniter\Config\Services::session()
#11 C:\xampp\htdocs\lltdemo\app\Controllers\BaseController.php(51): CodeIgniter\Config\BaseService::__callStatic('session', Array)
#12 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\CodeIgniter.php(867): App\Controllers\BaseController->initController(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), Object(CodeIgniter\Log\Logger))
#13 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\CodeIgniter.php(448): CodeIgniter\CodeIgniter->createController()
#14 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#15 C:\xampp\htdocs\lltdemo\public\index.php(67): CodeIgniter\CodeIgniter->run()
#16 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:215
Stack trace:
#0 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Session\Handlers\DatabaseHandler.php(91): CodeIgniter\Database\BaseConnection->initialize()
#2 [internal function]: CodeIgniter\Session\Handlers\DatabaseHandler->open('ci_sessions', 'ci_session')
#3 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Session\Session.php(918): session_start()
#4 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Session\Session.php(240): CodeIgniter\Session\Session->startSession()
#5 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Config\Services.php(665): CodeIgniter\Session\Session->start()
#6 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Config\BaseService.php(253): CodeIgniter\Config\Services::session(Object(Config\App), false)
#7 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Config\BaseService.php(194): CodeIgniter\Config\BaseService::__callStatic('session', Array)
#8 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Config\Services.php(637): CodeIgniter\Config\BaseService::getSharedInstance('session', NULL)
#9 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Config\BaseService.php(253): CodeIgniter\Config\Services::session()
#10 C:\xampp\htdocs\lltdemo\app\Controllers\BaseController.php(51): CodeIgniter\Config\BaseService::__callStatic('session', Array)
#11 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\CodeIgniter.php(867): App\Controllers\BaseController->initController(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), Object(CodeIgniter\Log\Logger))
#12 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\CodeIgniter.php(448): CodeIgniter\CodeIgniter->createController()
#13 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#14 C:\xampp\htdocs\lltdemo\public\index.php(67): CodeIgniter\CodeIgniter->run()
#15 {main}
CRITICAL - 2023-01-02 21:28:36 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 418.
 1 SYSTEMPATH\Session\Handlers\DatabaseHandler.php(91): CodeIgniter\Database\BaseConnection->initialize()
 2 [internal function]: CodeIgniter\Session\Handlers\DatabaseHandler->open('ci_sessions', 'ci_session')
 3 SYSTEMPATH\Session\Session.php(918): session_start()
 4 SYSTEMPATH\Session\Session.php(240): CodeIgniter\Session\Session->startSession()
 5 SYSTEMPATH\Config\Services.php(665): CodeIgniter\Session\Session->start()
 6 SYSTEMPATH\Config\BaseService.php(253): CodeIgniter\Config\Services::session(Object(Config\App), false)
 7 SYSTEMPATH\Config\BaseService.php(194): CodeIgniter\Config\BaseService::__callStatic('session', [...])
 8 SYSTEMPATH\Config\Services.php(637): CodeIgniter\Config\BaseService::getSharedInstance('session', null)
 9 SYSTEMPATH\Config\BaseService.php(253): CodeIgniter\Config\Services::session()
10 APPPATH\Controllers\BaseController.php(51): CodeIgniter\Config\BaseService::__callStatic('session', [])
11 SYSTEMPATH\CodeIgniter.php(867): App\Controllers\BaseController->initController(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), Object(CodeIgniter\Log\Logger))
12 SYSTEMPATH\CodeIgniter.php(448): CodeIgniter\CodeIgniter->createController()
13 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
14 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2023-01-02 21:28:38 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'regs2858_igni660'@'localhost' (using password: YES) in C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:171
Stack trace:
#0 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(171): mysqli->real_connect('localhost', 'regs2858_igni66...', '8m47Y6]S-p', 'regs2858_igni66...', 3306, '', 0)
#1 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Session\Handlers\DatabaseHandler.php(91): CodeIgniter\Database\BaseConnection->initialize()
#3 [internal function]: CodeIgniter\Session\Handlers\DatabaseHandler->open('ci_sessions', 'ci_session')
#4 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Session\Session.php(918): session_start()
#5 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Session\Session.php(240): CodeIgniter\Session\Session->startSession()
#6 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Config\Services.php(665): CodeIgniter\Session\Session->start()
#7 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Config\BaseService.php(253): CodeIgniter\Config\Services::session(Object(Config\App), false)
#8 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Config\BaseService.php(194): CodeIgniter\Config\BaseService::__callStatic('session', Array)
#9 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Config\Services.php(637): CodeIgniter\Config\BaseService::getSharedInstance('session', NULL)
#10 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Config\BaseService.php(253): CodeIgniter\Config\Services::session()
#11 C:\xampp\htdocs\lltdemo\app\Controllers\BaseController.php(51): CodeIgniter\Config\BaseService::__callStatic('session', Array)
#12 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\CodeIgniter.php(867): App\Controllers\BaseController->initController(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), Object(CodeIgniter\Log\Logger))
#13 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\CodeIgniter.php(448): CodeIgniter\CodeIgniter->createController()
#14 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#15 C:\xampp\htdocs\lltdemo\public\index.php(67): CodeIgniter\CodeIgniter->run()
#16 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:215
Stack trace:
#0 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Session\Handlers\DatabaseHandler.php(91): CodeIgniter\Database\BaseConnection->initialize()
#2 [internal function]: CodeIgniter\Session\Handlers\DatabaseHandler->open('ci_sessions', 'ci_session')
#3 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Session\Session.php(918): session_start()
#4 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Session\Session.php(240): CodeIgniter\Session\Session->startSession()
#5 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Config\Services.php(665): CodeIgniter\Session\Session->start()
#6 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Config\BaseService.php(253): CodeIgniter\Config\Services::session(Object(Config\App), false)
#7 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Config\BaseService.php(194): CodeIgniter\Config\BaseService::__callStatic('session', Array)
#8 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Config\Services.php(637): CodeIgniter\Config\BaseService::getSharedInstance('session', NULL)
#9 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Config\BaseService.php(253): CodeIgniter\Config\Services::session()
#10 C:\xampp\htdocs\lltdemo\app\Controllers\BaseController.php(51): CodeIgniter\Config\BaseService::__callStatic('session', Array)
#11 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\CodeIgniter.php(867): App\Controllers\BaseController->initController(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), Object(CodeIgniter\Log\Logger))
#12 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\CodeIgniter.php(448): CodeIgniter\CodeIgniter->createController()
#13 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#14 C:\xampp\htdocs\lltdemo\public\index.php(67): CodeIgniter\CodeIgniter->run()
#15 {main}
CRITICAL - 2023-01-02 21:28:38 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 418.
 1 SYSTEMPATH\Session\Handlers\DatabaseHandler.php(91): CodeIgniter\Database\BaseConnection->initialize()
 2 [internal function]: CodeIgniter\Session\Handlers\DatabaseHandler->open('ci_sessions', 'ci_session')
 3 SYSTEMPATH\Session\Session.php(918): session_start()
 4 SYSTEMPATH\Session\Session.php(240): CodeIgniter\Session\Session->startSession()
 5 SYSTEMPATH\Config\Services.php(665): CodeIgniter\Session\Session->start()
 6 SYSTEMPATH\Config\BaseService.php(253): CodeIgniter\Config\Services::session(Object(Config\App), false)
 7 SYSTEMPATH\Config\BaseService.php(194): CodeIgniter\Config\BaseService::__callStatic('session', [...])
 8 SYSTEMPATH\Config\Services.php(637): CodeIgniter\Config\BaseService::getSharedInstance('session', null)
 9 SYSTEMPATH\Config\BaseService.php(253): CodeIgniter\Config\Services::session()
10 APPPATH\Controllers\BaseController.php(51): CodeIgniter\Config\BaseService::__callStatic('session', [])
11 SYSTEMPATH\CodeIgniter.php(867): App\Controllers\BaseController->initController(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), Object(CodeIgniter\Log\Logger))
12 SYSTEMPATH\CodeIgniter.php(448): CodeIgniter\CodeIgniter->createController()
13 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
14 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2023-01-02 21:29:24 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'regs2858_igni660'@'localhost' (using password: YES) in C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:171
Stack trace:
#0 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(171): mysqli->real_connect('localhost', 'regs2858_igni66...', '8m47Y6]S-p', 'regs2858_igni66...', 3306, '', 0)
#1 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Session\Handlers\DatabaseHandler.php(91): CodeIgniter\Database\BaseConnection->initialize()
#3 [internal function]: CodeIgniter\Session\Handlers\DatabaseHandler->open('ci_sessions', 'ci_session')
#4 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Session\Session.php(918): session_start()
#5 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Session\Session.php(240): CodeIgniter\Session\Session->startSession()
#6 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Config\Services.php(665): CodeIgniter\Session\Session->start()
#7 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Config\BaseService.php(253): CodeIgniter\Config\Services::session(Object(Config\App), false)
#8 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Config\BaseService.php(194): CodeIgniter\Config\BaseService::__callStatic('session', Array)
#9 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Config\Services.php(637): CodeIgniter\Config\BaseService::getSharedInstance('session', NULL)
#10 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Config\BaseService.php(253): CodeIgniter\Config\Services::session()
#11 C:\xampp\htdocs\lltdemo\app\Controllers\BaseController.php(51): CodeIgniter\Config\BaseService::__callStatic('session', Array)
#12 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\CodeIgniter.php(867): App\Controllers\BaseController->initController(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), Object(CodeIgniter\Log\Logger))
#13 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\CodeIgniter.php(448): CodeIgniter\CodeIgniter->createController()
#14 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#15 C:\xampp\htdocs\lltdemo\public\index.php(67): CodeIgniter\CodeIgniter->run()
#16 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:215
Stack trace:
#0 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Session\Handlers\DatabaseHandler.php(91): CodeIgniter\Database\BaseConnection->initialize()
#2 [internal function]: CodeIgniter\Session\Handlers\DatabaseHandler->open('ci_sessions', 'ci_session')
#3 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Session\Session.php(918): session_start()
#4 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Session\Session.php(240): CodeIgniter\Session\Session->startSession()
#5 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Config\Services.php(665): CodeIgniter\Session\Session->start()
#6 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Config\BaseService.php(253): CodeIgniter\Config\Services::session(Object(Config\App), false)
#7 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Config\BaseService.php(194): CodeIgniter\Config\BaseService::__callStatic('session', Array)
#8 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Config\Services.php(637): CodeIgniter\Config\BaseService::getSharedInstance('session', NULL)
#9 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Config\BaseService.php(253): CodeIgniter\Config\Services::session()
#10 C:\xampp\htdocs\lltdemo\app\Controllers\BaseController.php(51): CodeIgniter\Config\BaseService::__callStatic('session', Array)
#11 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\CodeIgniter.php(867): App\Controllers\BaseController->initController(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), Object(CodeIgniter\Log\Logger))
#12 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\CodeIgniter.php(448): CodeIgniter\CodeIgniter->createController()
#13 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#14 C:\xampp\htdocs\lltdemo\public\index.php(67): CodeIgniter\CodeIgniter->run()
#15 {main}
CRITICAL - 2023-01-02 21:29:24 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 418.
 1 SYSTEMPATH\Session\Handlers\DatabaseHandler.php(91): CodeIgniter\Database\BaseConnection->initialize()
 2 [internal function]: CodeIgniter\Session\Handlers\DatabaseHandler->open('ci_sessions', 'ci_session')
 3 SYSTEMPATH\Session\Session.php(918): session_start()
 4 SYSTEMPATH\Session\Session.php(240): CodeIgniter\Session\Session->startSession()
 5 SYSTEMPATH\Config\Services.php(665): CodeIgniter\Session\Session->start()
 6 SYSTEMPATH\Config\BaseService.php(253): CodeIgniter\Config\Services::session(Object(Config\App), false)
 7 SYSTEMPATH\Config\BaseService.php(194): CodeIgniter\Config\BaseService::__callStatic('session', [...])
 8 SYSTEMPATH\Config\Services.php(637): CodeIgniter\Config\BaseService::getSharedInstance('session', null)
 9 SYSTEMPATH\Config\BaseService.php(253): CodeIgniter\Config\Services::session()
10 APPPATH\Controllers\BaseController.php(51): CodeIgniter\Config\BaseService::__callStatic('session', [])
11 SYSTEMPATH\CodeIgniter.php(867): App\Controllers\BaseController->initController(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), Object(CodeIgniter\Log\Logger))
12 SYSTEMPATH\CodeIgniter.php(448): CodeIgniter\CodeIgniter->createController()
13 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
14 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2023-01-02 21:29:25 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'regs2858_igni660'@'localhost' (using password: YES) in C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:171
Stack trace:
#0 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(171): mysqli->real_connect('localhost', 'regs2858_igni66...', '8m47Y6]S-p', 'regs2858_igni66...', 3306, '', 0)
#1 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Session\Handlers\DatabaseHandler.php(91): CodeIgniter\Database\BaseConnection->initialize()
#3 [internal function]: CodeIgniter\Session\Handlers\DatabaseHandler->open('ci_sessions', 'ci_session')
#4 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Session\Session.php(918): session_start()
#5 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Session\Session.php(240): CodeIgniter\Session\Session->startSession()
#6 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Config\Services.php(665): CodeIgniter\Session\Session->start()
#7 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Config\BaseService.php(253): CodeIgniter\Config\Services::session(Object(Config\App), false)
#8 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Config\BaseService.php(194): CodeIgniter\Config\BaseService::__callStatic('session', Array)
#9 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Config\Services.php(637): CodeIgniter\Config\BaseService::getSharedInstance('session', NULL)
#10 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Config\BaseService.php(253): CodeIgniter\Config\Services::session()
#11 C:\xampp\htdocs\lltdemo\app\Controllers\BaseController.php(51): CodeIgniter\Config\BaseService::__callStatic('session', Array)
#12 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\CodeIgniter.php(867): App\Controllers\BaseController->initController(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), Object(CodeIgniter\Log\Logger))
#13 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\CodeIgniter.php(448): CodeIgniter\CodeIgniter->createController()
#14 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#15 C:\xampp\htdocs\lltdemo\public\index.php(67): CodeIgniter\CodeIgniter->run()
#16 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:215
Stack trace:
#0 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Session\Handlers\DatabaseHandler.php(91): CodeIgniter\Database\BaseConnection->initialize()
#2 [internal function]: CodeIgniter\Session\Handlers\DatabaseHandler->open('ci_sessions', 'ci_session')
#3 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Session\Session.php(918): session_start()
#4 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Session\Session.php(240): CodeIgniter\Session\Session->startSession()
#5 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Config\Services.php(665): CodeIgniter\Session\Session->start()
#6 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Config\BaseService.php(253): CodeIgniter\Config\Services::session(Object(Config\App), false)
#7 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Config\BaseService.php(194): CodeIgniter\Config\BaseService::__callStatic('session', Array)
#8 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Config\Services.php(637): CodeIgniter\Config\BaseService::getSharedInstance('session', NULL)
#9 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Config\BaseService.php(253): CodeIgniter\Config\Services::session()
#10 C:\xampp\htdocs\lltdemo\app\Controllers\BaseController.php(51): CodeIgniter\Config\BaseService::__callStatic('session', Array)
#11 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\CodeIgniter.php(867): App\Controllers\BaseController->initController(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), Object(CodeIgniter\Log\Logger))
#12 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\CodeIgniter.php(448): CodeIgniter\CodeIgniter->createController()
#13 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#14 C:\xampp\htdocs\lltdemo\public\index.php(67): CodeIgniter\CodeIgniter->run()
#15 {main}
CRITICAL - 2023-01-02 21:29:25 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 418.
 1 SYSTEMPATH\Session\Handlers\DatabaseHandler.php(91): CodeIgniter\Database\BaseConnection->initialize()
 2 [internal function]: CodeIgniter\Session\Handlers\DatabaseHandler->open('ci_sessions', 'ci_session')
 3 SYSTEMPATH\Session\Session.php(918): session_start()
 4 SYSTEMPATH\Session\Session.php(240): CodeIgniter\Session\Session->startSession()
 5 SYSTEMPATH\Config\Services.php(665): CodeIgniter\Session\Session->start()
 6 SYSTEMPATH\Config\BaseService.php(253): CodeIgniter\Config\Services::session(Object(Config\App), false)
 7 SYSTEMPATH\Config\BaseService.php(194): CodeIgniter\Config\BaseService::__callStatic('session', [...])
 8 SYSTEMPATH\Config\Services.php(637): CodeIgniter\Config\BaseService::getSharedInstance('session', null)
 9 SYSTEMPATH\Config\BaseService.php(253): CodeIgniter\Config\Services::session()
10 APPPATH\Controllers\BaseController.php(51): CodeIgniter\Config\BaseService::__callStatic('session', [])
11 SYSTEMPATH\CodeIgniter.php(867): App\Controllers\BaseController->initController(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), Object(CodeIgniter\Log\Logger))
12 SYSTEMPATH\CodeIgniter.php(448): CodeIgniter\CodeIgniter->createController()
13 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
14 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2023-01-02 21:29:26 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'regs2858_igni660'@'localhost' (using password: YES) in C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:171
Stack trace:
#0 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(171): mysqli->real_connect('localhost', 'regs2858_igni66...', '8m47Y6]S-p', 'regs2858_igni66...', 3306, '', 0)
#1 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Session\Handlers\DatabaseHandler.php(91): CodeIgniter\Database\BaseConnection->initialize()
#3 [internal function]: CodeIgniter\Session\Handlers\DatabaseHandler->open('ci_sessions', 'ci_session')
#4 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Session\Session.php(918): session_start()
#5 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Session\Session.php(240): CodeIgniter\Session\Session->startSession()
#6 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Config\Services.php(665): CodeIgniter\Session\Session->start()
#7 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Config\BaseService.php(253): CodeIgniter\Config\Services::session(Object(Config\App), false)
#8 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Config\BaseService.php(194): CodeIgniter\Config\BaseService::__callStatic('session', Array)
#9 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Config\Services.php(637): CodeIgniter\Config\BaseService::getSharedInstance('session', NULL)
#10 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Config\BaseService.php(253): CodeIgniter\Config\Services::session()
#11 C:\xampp\htdocs\lltdemo\app\Controllers\BaseController.php(51): CodeIgniter\Config\BaseService::__callStatic('session', Array)
#12 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\CodeIgniter.php(867): App\Controllers\BaseController->initController(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), Object(CodeIgniter\Log\Logger))
#13 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\CodeIgniter.php(448): CodeIgniter\CodeIgniter->createController()
#14 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#15 C:\xampp\htdocs\lltdemo\public\index.php(67): CodeIgniter\CodeIgniter->run()
#16 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:215
Stack trace:
#0 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Session\Handlers\DatabaseHandler.php(91): CodeIgniter\Database\BaseConnection->initialize()
#2 [internal function]: CodeIgniter\Session\Handlers\DatabaseHandler->open('ci_sessions', 'ci_session')
#3 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Session\Session.php(918): session_start()
#4 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Session\Session.php(240): CodeIgniter\Session\Session->startSession()
#5 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Config\Services.php(665): CodeIgniter\Session\Session->start()
#6 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Config\BaseService.php(253): CodeIgniter\Config\Services::session(Object(Config\App), false)
#7 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Config\BaseService.php(194): CodeIgniter\Config\BaseService::__callStatic('session', Array)
#8 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Config\Services.php(637): CodeIgniter\Config\BaseService::getSharedInstance('session', NULL)
#9 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Config\BaseService.php(253): CodeIgniter\Config\Services::session()
#10 C:\xampp\htdocs\lltdemo\app\Controllers\BaseController.php(51): CodeIgniter\Config\BaseService::__callStatic('session', Array)
#11 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\CodeIgniter.php(867): App\Controllers\BaseController->initController(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), Object(CodeIgniter\Log\Logger))
#12 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\CodeIgniter.php(448): CodeIgniter\CodeIgniter->createController()
#13 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#14 C:\xampp\htdocs\lltdemo\public\index.php(67): CodeIgniter\CodeIgniter->run()
#15 {main}
CRITICAL - 2023-01-02 21:29:26 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 418.
 1 SYSTEMPATH\Session\Handlers\DatabaseHandler.php(91): CodeIgniter\Database\BaseConnection->initialize()
 2 [internal function]: CodeIgniter\Session\Handlers\DatabaseHandler->open('ci_sessions', 'ci_session')
 3 SYSTEMPATH\Session\Session.php(918): session_start()
 4 SYSTEMPATH\Session\Session.php(240): CodeIgniter\Session\Session->startSession()
 5 SYSTEMPATH\Config\Services.php(665): CodeIgniter\Session\Session->start()
 6 SYSTEMPATH\Config\BaseService.php(253): CodeIgniter\Config\Services::session(Object(Config\App), false)
 7 SYSTEMPATH\Config\BaseService.php(194): CodeIgniter\Config\BaseService::__callStatic('session', [...])
 8 SYSTEMPATH\Config\Services.php(637): CodeIgniter\Config\BaseService::getSharedInstance('session', null)
 9 SYSTEMPATH\Config\BaseService.php(253): CodeIgniter\Config\Services::session()
10 APPPATH\Controllers\BaseController.php(51): CodeIgniter\Config\BaseService::__callStatic('session', [])
11 SYSTEMPATH\CodeIgniter.php(867): App\Controllers\BaseController->initController(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), Object(CodeIgniter\Log\Logger))
12 SYSTEMPATH\CodeIgniter.php(448): CodeIgniter\CodeIgniter->createController()
13 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
14 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2023-01-02 21:29:26 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'regs2858_igni660'@'localhost' (using password: YES) in C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:171
Stack trace:
#0 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(171): mysqli->real_connect('localhost', 'regs2858_igni66...', '8m47Y6]S-p', 'regs2858_igni66...', 3306, '', 0)
#1 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Session\Handlers\DatabaseHandler.php(91): CodeIgniter\Database\BaseConnection->initialize()
#3 [internal function]: CodeIgniter\Session\Handlers\DatabaseHandler->open('ci_sessions', 'ci_session')
#4 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Session\Session.php(918): session_start()
#5 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Session\Session.php(240): CodeIgniter\Session\Session->startSession()
#6 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Config\Services.php(665): CodeIgniter\Session\Session->start()
#7 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Config\BaseService.php(253): CodeIgniter\Config\Services::session(Object(Config\App), false)
#8 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Config\BaseService.php(194): CodeIgniter\Config\BaseService::__callStatic('session', Array)
#9 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Config\Services.php(637): CodeIgniter\Config\BaseService::getSharedInstance('session', NULL)
#10 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Config\BaseService.php(253): CodeIgniter\Config\Services::session()
#11 C:\xampp\htdocs\lltdemo\app\Controllers\BaseController.php(51): CodeIgniter\Config\BaseService::__callStatic('session', Array)
#12 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\CodeIgniter.php(867): App\Controllers\BaseController->initController(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), Object(CodeIgniter\Log\Logger))
#13 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\CodeIgniter.php(448): CodeIgniter\CodeIgniter->createController()
#14 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#15 C:\xampp\htdocs\lltdemo\public\index.php(67): CodeIgniter\CodeIgniter->run()
#16 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:215
Stack trace:
#0 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Session\Handlers\DatabaseHandler.php(91): CodeIgniter\Database\BaseConnection->initialize()
#2 [internal function]: CodeIgniter\Session\Handlers\DatabaseHandler->open('ci_sessions', 'ci_session')
#3 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Session\Session.php(918): session_start()
#4 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Session\Session.php(240): CodeIgniter\Session\Session->startSession()
#5 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Config\Services.php(665): CodeIgniter\Session\Session->start()
#6 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Config\BaseService.php(253): CodeIgniter\Config\Services::session(Object(Config\App), false)
#7 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Config\BaseService.php(194): CodeIgniter\Config\BaseService::__callStatic('session', Array)
#8 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Config\Services.php(637): CodeIgniter\Config\BaseService::getSharedInstance('session', NULL)
#9 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Config\BaseService.php(253): CodeIgniter\Config\Services::session()
#10 C:\xampp\htdocs\lltdemo\app\Controllers\BaseController.php(51): CodeIgniter\Config\BaseService::__callStatic('session', Array)
#11 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\CodeIgniter.php(867): App\Controllers\BaseController->initController(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), Object(CodeIgniter\Log\Logger))
#12 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\CodeIgniter.php(448): CodeIgniter\CodeIgniter->createController()
#13 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#14 C:\xampp\htdocs\lltdemo\public\index.php(67): CodeIgniter\CodeIgniter->run()
#15 {main}
CRITICAL - 2023-01-02 21:29:26 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 418.
 1 SYSTEMPATH\Session\Handlers\DatabaseHandler.php(91): CodeIgniter\Database\BaseConnection->initialize()
 2 [internal function]: CodeIgniter\Session\Handlers\DatabaseHandler->open('ci_sessions', 'ci_session')
 3 SYSTEMPATH\Session\Session.php(918): session_start()
 4 SYSTEMPATH\Session\Session.php(240): CodeIgniter\Session\Session->startSession()
 5 SYSTEMPATH\Config\Services.php(665): CodeIgniter\Session\Session->start()
 6 SYSTEMPATH\Config\BaseService.php(253): CodeIgniter\Config\Services::session(Object(Config\App), false)
 7 SYSTEMPATH\Config\BaseService.php(194): CodeIgniter\Config\BaseService::__callStatic('session', [...])
 8 SYSTEMPATH\Config\Services.php(637): CodeIgniter\Config\BaseService::getSharedInstance('session', null)
 9 SYSTEMPATH\Config\BaseService.php(253): CodeIgniter\Config\Services::session()
10 APPPATH\Controllers\BaseController.php(51): CodeIgniter\Config\BaseService::__callStatic('session', [])
11 SYSTEMPATH\CodeIgniter.php(867): App\Controllers\BaseController->initController(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), Object(CodeIgniter\Log\Logger))
12 SYSTEMPATH\CodeIgniter.php(448): CodeIgniter\CodeIgniter->createController()
13 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
14 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2023-01-02 21:29:27 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'regs2858_igni660'@'localhost' (using password: YES) in C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:171
Stack trace:
#0 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(171): mysqli->real_connect('localhost', 'regs2858_igni66...', '8m47Y6]S-p', 'regs2858_igni66...', 3306, '', 0)
#1 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Session\Handlers\DatabaseHandler.php(91): CodeIgniter\Database\BaseConnection->initialize()
#3 [internal function]: CodeIgniter\Session\Handlers\DatabaseHandler->open('ci_sessions', 'ci_session')
#4 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Session\Session.php(918): session_start()
#5 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Session\Session.php(240): CodeIgniter\Session\Session->startSession()
#6 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Config\Services.php(665): CodeIgniter\Session\Session->start()
#7 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Config\BaseService.php(253): CodeIgniter\Config\Services::session(Object(Config\App), false)
#8 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Config\BaseService.php(194): CodeIgniter\Config\BaseService::__callStatic('session', Array)
#9 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Config\Services.php(637): CodeIgniter\Config\BaseService::getSharedInstance('session', NULL)
#10 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Config\BaseService.php(253): CodeIgniter\Config\Services::session()
#11 C:\xampp\htdocs\lltdemo\app\Controllers\BaseController.php(51): CodeIgniter\Config\BaseService::__callStatic('session', Array)
#12 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\CodeIgniter.php(867): App\Controllers\BaseController->initController(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), Object(CodeIgniter\Log\Logger))
#13 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\CodeIgniter.php(448): CodeIgniter\CodeIgniter->createController()
#14 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#15 C:\xampp\htdocs\lltdemo\public\index.php(67): CodeIgniter\CodeIgniter->run()
#16 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:215
Stack trace:
#0 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Session\Handlers\DatabaseHandler.php(91): CodeIgniter\Database\BaseConnection->initialize()
#2 [internal function]: CodeIgniter\Session\Handlers\DatabaseHandler->open('ci_sessions', 'ci_session')
#3 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Session\Session.php(918): session_start()
#4 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Session\Session.php(240): CodeIgniter\Session\Session->startSession()
#5 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Config\Services.php(665): CodeIgniter\Session\Session->start()
#6 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Config\BaseService.php(253): CodeIgniter\Config\Services::session(Object(Config\App), false)
#7 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Config\BaseService.php(194): CodeIgniter\Config\BaseService::__callStatic('session', Array)
#8 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Config\Services.php(637): CodeIgniter\Config\BaseService::getSharedInstance('session', NULL)
#9 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\Config\BaseService.php(253): CodeIgniter\Config\Services::session()
#10 C:\xampp\htdocs\lltdemo\app\Controllers\BaseController.php(51): CodeIgniter\Config\BaseService::__callStatic('session', Array)
#11 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\CodeIgniter.php(867): App\Controllers\BaseController->initController(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), Object(CodeIgniter\Log\Logger))
#12 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\CodeIgniter.php(448): CodeIgniter\CodeIgniter->createController()
#13 C:\xampp\htdocs\lltdemo\vendor\codeigniter4\framework\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#14 C:\xampp\htdocs\lltdemo\public\index.php(67): CodeIgniter\CodeIgniter->run()
#15 {main}
CRITICAL - 2023-01-02 21:29:27 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 418.
 1 SYSTEMPATH\Session\Handlers\DatabaseHandler.php(91): CodeIgniter\Database\BaseConnection->initialize()
 2 [internal function]: CodeIgniter\Session\Handlers\DatabaseHandler->open('ci_sessions', 'ci_session')
 3 SYSTEMPATH\Session\Session.php(918): session_start()
 4 SYSTEMPATH\Session\Session.php(240): CodeIgniter\Session\Session->startSession()
 5 SYSTEMPATH\Config\Services.php(665): CodeIgniter\Session\Session->start()
 6 SYSTEMPATH\Config\BaseService.php(253): CodeIgniter\Config\Services::session(Object(Config\App), false)
 7 SYSTEMPATH\Config\BaseService.php(194): CodeIgniter\Config\BaseService::__callStatic('session', [...])
 8 SYSTEMPATH\Config\Services.php(637): CodeIgniter\Config\BaseService::getSharedInstance('session', null)
 9 SYSTEMPATH\Config\BaseService.php(253): CodeIgniter\Config\Services::session()
10 APPPATH\Controllers\BaseController.php(51): CodeIgniter\Config\BaseService::__callStatic('session', [])
11 SYSTEMPATH\CodeIgniter.php(867): App\Controllers\BaseController->initController(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), Object(CodeIgniter\Log\Logger))
12 SYSTEMPATH\CodeIgniter.php(448): CodeIgniter\CodeIgniter->createController()
13 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
14 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
